// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/outbox/domain/repositories (interfaces: OutboxRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/outbox_repository_mock.go -package=mocks . OutboxRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/LerianStudio/matcher/internal/outbox/domain/entities"
	repositories "github.com/LerianStudio/matcher/internal/outbox/domain/repositories"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboxRepository is a mock of OutboxRepository interface.
type MockOutboxRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboxRepositoryMockRecorder is the mock recorder for MockOutboxRepository.
type MockOutboxRepositoryMockRecorder struct {
	mock *MockOutboxRepository
}

// NewMockOutboxRepository creates a new mock instance.
func NewMockOutboxRepository(ctrl *gomock.Controller) *MockOutboxRepository {
	mock := &MockOutboxRepository{ctrl: ctrl}
	mock.recorder = &MockOutboxRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepository) EXPECT() *MockOutboxRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOutboxRepository) Create(ctx context.Context, event *entities.OutboxEvent) (*entities.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, event)
	ret0, _ := ret[0].(*entities.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOutboxRepositoryMockRecorder) Create(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOutboxRepository)(nil).Create), ctx, event)
}

// CreateWithTx mocks base method.
func (m *MockOutboxRepository) CreateWithTx(ctx context.Context, tx repositories.Tx, event *entities.OutboxEvent) (*entities.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, tx, event)
	ret0, _ := ret[0].(*entities.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockOutboxRepositoryMockRecorder) CreateWithTx(ctx, tx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockOutboxRepository)(nil).CreateWithTx), ctx, tx, event)
}

// GetByID mocks base method.
func (m *MockOutboxRepository) GetByID(ctx context.Context, id uuid.UUID) (*entities.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOutboxRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOutboxRepository)(nil).GetByID), ctx, id)
}

// ListFailedForRetry mocks base method.
func (m *MockOutboxRepository) ListFailedForRetry(ctx context.Context, limit int, failedBefore time.Time, maxAttempts int) ([]*entities.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFailedForRetry", ctx, limit, failedBefore, maxAttempts)
	ret0, _ := ret[0].([]*entities.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFailedForRetry indicates an expected call of ListFailedForRetry.
func (mr *MockOutboxRepositoryMockRecorder) ListFailedForRetry(ctx, limit, failedBefore, maxAttempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFailedForRetry", reflect.TypeOf((*MockOutboxRepository)(nil).ListFailedForRetry), ctx, limit, failedBefore, maxAttempts)
}

// ListPending mocks base method.
func (m *MockOutboxRepository) ListPending(ctx context.Context, limit int) ([]*entities.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx, limit)
	ret0, _ := ret[0].([]*entities.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockOutboxRepositoryMockRecorder) ListPending(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockOutboxRepository)(nil).ListPending), ctx, limit)
}

// ListPendingByType mocks base method.
func (m *MockOutboxRepository) ListPendingByType(ctx context.Context, eventType string, limit int) ([]*entities.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingByType", ctx, eventType, limit)
	ret0, _ := ret[0].([]*entities.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingByType indicates an expected call of ListPendingByType.
func (mr *MockOutboxRepositoryMockRecorder) ListPendingByType(ctx, eventType, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingByType", reflect.TypeOf((*MockOutboxRepository)(nil).ListPendingByType), ctx, eventType, limit)
}

// ListTenants mocks base method.
func (m *MockOutboxRepository) ListTenants(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTenants", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTenants indicates an expected call of ListTenants.
func (mr *MockOutboxRepositoryMockRecorder) ListTenants(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTenants", reflect.TypeOf((*MockOutboxRepository)(nil).ListTenants), ctx)
}

// MarkFailed mocks base method.
func (m *MockOutboxRepository) MarkFailed(ctx context.Context, id uuid.UUID, errMsg string, maxAttempts int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, id, errMsg, maxAttempts)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockOutboxRepositoryMockRecorder) MarkFailed(ctx, id, errMsg, maxAttempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockOutboxRepository)(nil).MarkFailed), ctx, id, errMsg, maxAttempts)
}

// MarkInvalid mocks base method.
func (m *MockOutboxRepository) MarkInvalid(ctx context.Context, id uuid.UUID, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkInvalid", ctx, id, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkInvalid indicates an expected call of MarkInvalid.
func (mr *MockOutboxRepositoryMockRecorder) MarkInvalid(ctx, id, errMsg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkInvalid", reflect.TypeOf((*MockOutboxRepository)(nil).MarkInvalid), ctx, id, errMsg)
}

// MarkPublished mocks base method.
func (m *MockOutboxRepository) MarkPublished(ctx context.Context, id uuid.UUID, publishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPublished", ctx, id, publishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPublished indicates an expected call of MarkPublished.
func (mr *MockOutboxRepositoryMockRecorder) MarkPublished(ctx, id, publishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPublished", reflect.TypeOf((*MockOutboxRepository)(nil).MarkPublished), ctx, id, publishedAt)
}

// ResetForRetry mocks base method.
func (m *MockOutboxRepository) ResetForRetry(ctx context.Context, limit int, failedBefore time.Time, maxAttempts int) ([]*entities.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetForRetry", ctx, limit, failedBefore, maxAttempts)
	ret0, _ := ret[0].([]*entities.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetForRetry indicates an expected call of ResetForRetry.
func (mr *MockOutboxRepositoryMockRecorder) ResetForRetry(ctx, limit, failedBefore, maxAttempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetForRetry", reflect.TypeOf((*MockOutboxRepository)(nil).ResetForRetry), ctx, limit, failedBefore, maxAttempts)
}

// ResetStuckProcessing mocks base method.
func (m *MockOutboxRepository) ResetStuckProcessing(ctx context.Context, limit int, processingBefore time.Time, maxAttempts int) ([]*entities.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetStuckProcessing", ctx, limit, processingBefore, maxAttempts)
	ret0, _ := ret[0].([]*entities.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetStuckProcessing indicates an expected call of ResetStuckProcessing.
func (mr *MockOutboxRepositoryMockRecorder) ResetStuckProcessing(ctx, limit, processingBefore, maxAttempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetStuckProcessing", reflect.TypeOf((*MockOutboxRepository)(nil).ResetStuckProcessing), ctx, limit, processingBefore, maxAttempts)
}
