// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/exception/domain/repositories (interfaces: CallbackIdempotencyRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/callback_idempotency_repository_mock.go -package=mocks . CallbackIdempotencyRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	value_objects "github.com/LerianStudio/matcher/internal/exception/domain/value_objects"
	gomock "go.uber.org/mock/gomock"
)

// MockCallbackIdempotencyRepository is a mock of CallbackIdempotencyRepository interface.
type MockCallbackIdempotencyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCallbackIdempotencyRepositoryMockRecorder
	isgomock struct{}
}

// MockCallbackIdempotencyRepositoryMockRecorder is the mock recorder for MockCallbackIdempotencyRepository.
type MockCallbackIdempotencyRepositoryMockRecorder struct {
	mock *MockCallbackIdempotencyRepository
}

// NewMockCallbackIdempotencyRepository creates a new mock instance.
func NewMockCallbackIdempotencyRepository(ctrl *gomock.Controller) *MockCallbackIdempotencyRepository {
	mock := &MockCallbackIdempotencyRepository{ctrl: ctrl}
	mock.recorder = &MockCallbackIdempotencyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCallbackIdempotencyRepository) EXPECT() *MockCallbackIdempotencyRepositoryMockRecorder {
	return m.recorder
}

// GetCachedResult mocks base method.
func (m *MockCallbackIdempotencyRepository) GetCachedResult(ctx context.Context, key value_objects.IdempotencyKey) (*value_objects.IdempotencyResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedResult", ctx, key)
	ret0, _ := ret[0].(*value_objects.IdempotencyResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedResult indicates an expected call of GetCachedResult.
func (mr *MockCallbackIdempotencyRepositoryMockRecorder) GetCachedResult(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedResult", reflect.TypeOf((*MockCallbackIdempotencyRepository)(nil).GetCachedResult), ctx, key)
}

// MarkComplete mocks base method.
func (m *MockCallbackIdempotencyRepository) MarkComplete(ctx context.Context, key value_objects.IdempotencyKey, response []byte, httpStatus int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkComplete", ctx, key, response, httpStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkComplete indicates an expected call of MarkComplete.
func (mr *MockCallbackIdempotencyRepositoryMockRecorder) MarkComplete(ctx, key, response, httpStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkComplete", reflect.TypeOf((*MockCallbackIdempotencyRepository)(nil).MarkComplete), ctx, key, response, httpStatus)
}

// MarkFailed mocks base method.
func (m *MockCallbackIdempotencyRepository) MarkFailed(ctx context.Context, key value_objects.IdempotencyKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockCallbackIdempotencyRepositoryMockRecorder) MarkFailed(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockCallbackIdempotencyRepository)(nil).MarkFailed), ctx, key)
}

// TryAcquire mocks base method.
func (m *MockCallbackIdempotencyRepository) TryAcquire(ctx context.Context, key value_objects.IdempotencyKey) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TryAcquire", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TryAcquire indicates an expected call of TryAcquire.
func (mr *MockCallbackIdempotencyRepositoryMockRecorder) TryAcquire(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TryAcquire", reflect.TypeOf((*MockCallbackIdempotencyRepository)(nil).TryAcquire), ctx, key)
}
