// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/exception/domain/repositories (interfaces: DisputeRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/dispute_repository_mock.go -package=mocks . DisputeRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	http "github.com/LerianStudio/lib-uncommons/v2/uncommons/net/http"
	dispute "github.com/LerianStudio/matcher/internal/exception/domain/dispute"
	repositories "github.com/LerianStudio/matcher/internal/exception/domain/repositories"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDisputeRepository is a mock of DisputeRepository interface.
type MockDisputeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDisputeRepositoryMockRecorder
	isgomock struct{}
}

// MockDisputeRepositoryMockRecorder is the mock recorder for MockDisputeRepository.
type MockDisputeRepositoryMockRecorder struct {
	mock *MockDisputeRepository
}

// NewMockDisputeRepository creates a new mock instance.
func NewMockDisputeRepository(ctrl *gomock.Controller) *MockDisputeRepository {
	mock := &MockDisputeRepository{ctrl: ctrl}
	mock.recorder = &MockDisputeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisputeRepository) EXPECT() *MockDisputeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDisputeRepository) Create(ctx context.Context, d *dispute.Dispute) (*dispute.Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, d)
	ret0, _ := ret[0].(*dispute.Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDisputeRepositoryMockRecorder) Create(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDisputeRepository)(nil).Create), ctx, d)
}

// CreateWithTx mocks base method.
func (m *MockDisputeRepository) CreateWithTx(ctx context.Context, tx repositories.Tx, d *dispute.Dispute) (*dispute.Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, tx, d)
	ret0, _ := ret[0].(*dispute.Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockDisputeRepositoryMockRecorder) CreateWithTx(ctx, tx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockDisputeRepository)(nil).CreateWithTx), ctx, tx, d)
}

// FindByExceptionID mocks base method.
func (m *MockDisputeRepository) FindByExceptionID(ctx context.Context, exceptionID uuid.UUID) (*dispute.Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByExceptionID", ctx, exceptionID)
	ret0, _ := ret[0].(*dispute.Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByExceptionID indicates an expected call of FindByExceptionID.
func (mr *MockDisputeRepositoryMockRecorder) FindByExceptionID(ctx, exceptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByExceptionID", reflect.TypeOf((*MockDisputeRepository)(nil).FindByExceptionID), ctx, exceptionID)
}

// FindByID mocks base method.
func (m *MockDisputeRepository) FindByID(ctx context.Context, id uuid.UUID) (*dispute.Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*dispute.Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockDisputeRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDisputeRepository)(nil).FindByID), ctx, id)
}

// List mocks base method.
func (m *MockDisputeRepository) List(ctx context.Context, filter repositories.DisputeFilter, cursor repositories.CursorFilter) ([]*dispute.Dispute, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, cursor)
	ret0, _ := ret[0].([]*dispute.Dispute)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockDisputeRepositoryMockRecorder) List(ctx, filter, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDisputeRepository)(nil).List), ctx, filter, cursor)
}

// Update mocks base method.
func (m *MockDisputeRepository) Update(ctx context.Context, d *dispute.Dispute) (*dispute.Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, d)
	ret0, _ := ret[0].(*dispute.Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDisputeRepositoryMockRecorder) Update(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDisputeRepository)(nil).Update), ctx, d)
}

// UpdateWithTx mocks base method.
func (m *MockDisputeRepository) UpdateWithTx(ctx context.Context, tx repositories.Tx, d *dispute.Dispute) (*dispute.Dispute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithTx", ctx, tx, d)
	ret0, _ := ret[0].(*dispute.Dispute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWithTx indicates an expected call of UpdateWithTx.
func (mr *MockDisputeRepositoryMockRecorder) UpdateWithTx(ctx, tx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithTx", reflect.TypeOf((*MockDisputeRepository)(nil).UpdateWithTx), ctx, tx, d)
}
