// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/exception/domain/repositories (interfaces: ExceptionRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/exception_repository_mock.go -package=mocks . ExceptionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	http "github.com/LerianStudio/lib-uncommons/v2/uncommons/net/http"
	entities "github.com/LerianStudio/matcher/internal/exception/domain/entities"
	repositories "github.com/LerianStudio/matcher/internal/exception/domain/repositories"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockExceptionRepository is a mock of ExceptionRepository interface.
type MockExceptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExceptionRepositoryMockRecorder
	isgomock struct{}
}

// MockExceptionRepositoryMockRecorder is the mock recorder for MockExceptionRepository.
type MockExceptionRepositoryMockRecorder struct {
	mock *MockExceptionRepository
}

// NewMockExceptionRepository creates a new mock instance.
func NewMockExceptionRepository(ctrl *gomock.Controller) *MockExceptionRepository {
	mock := &MockExceptionRepository{ctrl: ctrl}
	mock.recorder = &MockExceptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExceptionRepository) EXPECT() *MockExceptionRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockExceptionRepository) FindByID(ctx context.Context, id uuid.UUID) (*entities.Exception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entities.Exception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockExceptionRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockExceptionRepository)(nil).FindByID), ctx, id)
}

// List mocks base method.
func (m *MockExceptionRepository) List(ctx context.Context, filter repositories.ExceptionFilter, cursor repositories.CursorFilter) ([]*entities.Exception, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, cursor)
	ret0, _ := ret[0].([]*entities.Exception)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockExceptionRepositoryMockRecorder) List(ctx, filter, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExceptionRepository)(nil).List), ctx, filter, cursor)
}

// Update mocks base method.
func (m *MockExceptionRepository) Update(ctx context.Context, exception *entities.Exception) (*entities.Exception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, exception)
	ret0, _ := ret[0].(*entities.Exception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExceptionRepositoryMockRecorder) Update(ctx, exception any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExceptionRepository)(nil).Update), ctx, exception)
}

// UpdateWithTx mocks base method.
func (m *MockExceptionRepository) UpdateWithTx(ctx context.Context, tx repositories.Tx, exception *entities.Exception) (*entities.Exception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithTx", ctx, tx, exception)
	ret0, _ := ret[0].(*entities.Exception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWithTx indicates an expected call of UpdateWithTx.
func (mr *MockExceptionRepositoryMockRecorder) UpdateWithTx(ctx, tx, exception any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithTx", reflect.TypeOf((*MockExceptionRepository)(nil).UpdateWithTx), ctx, tx, exception)
}
