// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/exception/ports (interfaces: ActorExtractor)
//
// Generated by this command:
//
//	mockgen -destination=mocks/actor_extractor_mock.go -package=mocks . ActorExtractor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockActorExtractor is a mock of ActorExtractor interface.
type MockActorExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockActorExtractorMockRecorder
	isgomock struct{}
}

// MockActorExtractorMockRecorder is the mock recorder for MockActorExtractor.
type MockActorExtractorMockRecorder struct {
	mock *MockActorExtractor
}

// NewMockActorExtractor creates a new mock instance.
func NewMockActorExtractor(ctrl *gomock.Controller) *MockActorExtractor {
	mock := &MockActorExtractor{ctrl: ctrl}
	mock.recorder = &MockActorExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorExtractor) EXPECT() *MockActorExtractorMockRecorder {
	return m.recorder
}

// GetActor mocks base method.
func (m *MockActorExtractor) GetActor(ctx context.Context) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActor", ctx)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetActor indicates an expected call of GetActor.
func (mr *MockActorExtractorMockRecorder) GetActor(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActor", reflect.TypeOf((*MockActorExtractor)(nil).GetActor), ctx)
}
