// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/exception/ports (interfaces: AuditPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/audit_publisher_mock.go -package=mocks . AuditPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	ports "github.com/LerianStudio/matcher/internal/exception/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditPublisher is a mock of AuditPublisher interface.
type MockAuditPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockAuditPublisherMockRecorder
	isgomock struct{}
}

// MockAuditPublisherMockRecorder is the mock recorder for MockAuditPublisher.
type MockAuditPublisherMockRecorder struct {
	mock *MockAuditPublisher
}

// NewMockAuditPublisher creates a new mock instance.
func NewMockAuditPublisher(ctrl *gomock.Controller) *MockAuditPublisher {
	mock := &MockAuditPublisher{ctrl: ctrl}
	mock.recorder = &MockAuditPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditPublisher) EXPECT() *MockAuditPublisherMockRecorder {
	return m.recorder
}

// PublishExceptionEvent mocks base method.
func (m *MockAuditPublisher) PublishExceptionEvent(ctx context.Context, event ports.AuditEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishExceptionEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishExceptionEvent indicates an expected call of PublishExceptionEvent.
func (mr *MockAuditPublisherMockRecorder) PublishExceptionEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishExceptionEvent", reflect.TypeOf((*MockAuditPublisher)(nil).PublishExceptionEvent), ctx, event)
}

// PublishExceptionEventWithTx mocks base method.
func (m *MockAuditPublisher) PublishExceptionEventWithTx(ctx context.Context, tx *sql.Tx, event ports.AuditEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishExceptionEventWithTx", ctx, tx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishExceptionEventWithTx indicates an expected call of PublishExceptionEventWithTx.
func (mr *MockAuditPublisherMockRecorder) PublishExceptionEventWithTx(ctx, tx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishExceptionEventWithTx", reflect.TypeOf((*MockAuditPublisher)(nil).PublishExceptionEventWithTx), ctx, tx, event)
}
