// Code generated by hand; follows the pattern of other mocks in this package.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
)

// MockCallbackRateLimiter is a mock implementation of ports.CallbackRateLimiter.
type MockCallbackRateLimiter struct {
	mock.Mock
}

// Allow checks whether a callback from the given key is within the configured rate limit.
func (m *MockCallbackRateLimiter) Allow(ctx context.Context, key string) (bool, error) {
	args := m.Called(ctx, key)
	return args.Bool(0), args.Error(1)
}
