// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/exception/ports (interfaces: ExceptionFinder)
//
// Generated by this command:
//
//	mockgen -destination=mocks/exception_finder_mock.go -package=mocks . ExceptionFinder
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/LerianStudio/matcher/internal/exception/domain/entities"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockExceptionFinder is a mock of ExceptionFinder interface.
type MockExceptionFinder struct {
	ctrl     *gomock.Controller
	recorder *MockExceptionFinderMockRecorder
	isgomock struct{}
}

// MockExceptionFinderMockRecorder is the mock recorder for MockExceptionFinder.
type MockExceptionFinderMockRecorder struct {
	mock *MockExceptionFinder
}

// NewMockExceptionFinder creates a new mock instance.
func NewMockExceptionFinder(ctrl *gomock.Controller) *MockExceptionFinder {
	mock := &MockExceptionFinder{ctrl: ctrl}
	mock.recorder = &MockExceptionFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExceptionFinder) EXPECT() *MockExceptionFinderMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockExceptionFinder) FindByID(ctx context.Context, id uuid.UUID) (*entities.Exception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entities.Exception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockExceptionFinderMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockExceptionFinder)(nil).FindByID), ctx, id)
}
