// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/exception/ports (interfaces: ExternalConnector)
//
// Generated by this command:
//
//	mockgen -destination=mocks/external_connector_mock.go -package=mocks . ExternalConnector
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	services "github.com/LerianStudio/matcher/internal/exception/domain/services"
	ports "github.com/LerianStudio/matcher/internal/exception/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockExternalConnector is a mock of ExternalConnector interface.
type MockExternalConnector struct {
	ctrl     *gomock.Controller
	recorder *MockExternalConnectorMockRecorder
	isgomock struct{}
}

// MockExternalConnectorMockRecorder is the mock recorder for MockExternalConnector.
type MockExternalConnectorMockRecorder struct {
	mock *MockExternalConnector
}

// NewMockExternalConnector creates a new mock instance.
func NewMockExternalConnector(ctrl *gomock.Controller) *MockExternalConnector {
	mock := &MockExternalConnector{ctrl: ctrl}
	mock.recorder = &MockExternalConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalConnector) EXPECT() *MockExternalConnectorMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockExternalConnector) Dispatch(ctx context.Context, exceptionID string, decision services.RoutingDecision, payload []byte) (ports.DispatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dispatch", ctx, exceptionID, decision, payload)
	ret0, _ := ret[0].(ports.DispatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockExternalConnectorMockRecorder) Dispatch(ctx, exceptionID, decision, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockExternalConnector)(nil).Dispatch), ctx, exceptionID, decision, payload)
}
