// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/exception/ports (interfaces: MatchingGateway)
//
// Generated by this command:
//
//	mockgen -destination=mocks/matching_gateway_mock.go -package=mocks . MatchingGateway
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ports "github.com/LerianStudio/matcher/internal/exception/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchingGateway is a mock of MatchingGateway interface.
type MockMatchingGateway struct {
	ctrl     *gomock.Controller
	recorder *MockMatchingGatewayMockRecorder
	isgomock struct{}
}

// MockMatchingGatewayMockRecorder is the mock recorder for MockMatchingGateway.
type MockMatchingGatewayMockRecorder struct {
	mock *MockMatchingGateway
}

// NewMockMatchingGateway creates a new mock instance.
func NewMockMatchingGateway(ctrl *gomock.Controller) *MockMatchingGateway {
	mock := &MockMatchingGateway{ctrl: ctrl}
	mock.recorder = &MockMatchingGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchingGateway) EXPECT() *MockMatchingGatewayMockRecorder {
	return m.recorder
}

// CreateAdjustment mocks base method.
func (m *MockMatchingGateway) CreateAdjustment(ctx context.Context, input ports.CreateAdjustmentInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdjustment", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAdjustment indicates an expected call of CreateAdjustment.
func (mr *MockMatchingGatewayMockRecorder) CreateAdjustment(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdjustment", reflect.TypeOf((*MockMatchingGateway)(nil).CreateAdjustment), ctx, input)
}

// CreateForceMatch mocks base method.
func (m *MockMatchingGateway) CreateForceMatch(ctx context.Context, input ports.ForceMatchInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateForceMatch", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateForceMatch indicates an expected call of CreateForceMatch.
func (mr *MockMatchingGatewayMockRecorder) CreateForceMatch(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateForceMatch", reflect.TypeOf((*MockMatchingGateway)(nil).CreateForceMatch), ctx, input)
}
