// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/exception/ports (interfaces: ResolutionExecutor)
//
// Generated by this command:
//
//	mockgen -destination=mocks/resolution_executor_mock.go -package=mocks . ResolutionExecutor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	value_objects "github.com/LerianStudio/matcher/internal/exception/domain/value_objects"
	ports "github.com/LerianStudio/matcher/internal/exception/ports"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockResolutionExecutor is a mock of ResolutionExecutor interface.
type MockResolutionExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockResolutionExecutorMockRecorder
	isgomock struct{}
}

// MockResolutionExecutorMockRecorder is the mock recorder for MockResolutionExecutor.
type MockResolutionExecutorMockRecorder struct {
	mock *MockResolutionExecutor
}

// NewMockResolutionExecutor creates a new mock instance.
func NewMockResolutionExecutor(ctrl *gomock.Controller) *MockResolutionExecutor {
	mock := &MockResolutionExecutor{ctrl: ctrl}
	mock.recorder = &MockResolutionExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolutionExecutor) EXPECT() *MockResolutionExecutorMockRecorder {
	return m.recorder
}

// AdjustEntry mocks base method.
func (m *MockResolutionExecutor) AdjustEntry(ctx context.Context, exceptionID uuid.UUID, input ports.AdjustmentInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdjustEntry", ctx, exceptionID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdjustEntry indicates an expected call of AdjustEntry.
func (mr *MockResolutionExecutorMockRecorder) AdjustEntry(ctx, exceptionID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdjustEntry", reflect.TypeOf((*MockResolutionExecutor)(nil).AdjustEntry), ctx, exceptionID, input)
}

// ForceMatch mocks base method.
func (m *MockResolutionExecutor) ForceMatch(ctx context.Context, exceptionID uuid.UUID, notes string, overrideReason value_objects.OverrideReason) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForceMatch", ctx, exceptionID, notes, overrideReason)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceMatch indicates an expected call of ForceMatch.
func (mr *MockResolutionExecutorMockRecorder) ForceMatch(ctx, exceptionID, notes, overrideReason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceMatch", reflect.TypeOf((*MockResolutionExecutor)(nil).ForceMatch), ctx, exceptionID, notes, overrideReason)
}
