tagFormat: "v${version}"

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "conventionalcommits"
      parserOpts:
        noteKeywords:
          - "BREAKING CHANGE"
          - "BREAKING CHANGES"
      releaseRules:
        - type: "feat"
          release: "minor"
        - type: "fix"
          release: "patch"
        - type: "perf"
          release: "minor"
        - type: "refactor"
          release: "minor"
        - type: "build"
          release: "patch"
        - type: "chore"
          release: "patch"
        - type: "ci"
          release: "patch"
        - type: "docs"
          release: "patch"
        - type: "test"
          release: "patch"
        - breaking: true
          release: "major"

  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
      parserOpts:
        noteKeywords:
          - "BREAKING CHANGE"
          - "BREAKING CHANGES"
          - "BREAKING"
      writerOpts:
        commitsSort:
          - "subject"
          - "scope"

  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"

  - - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
      message: "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"

  - - "@semantic-release/github"
    - assets:
        - path: "CHANGELOG.md"
          label: "Changelog"

  - - "@saithodev/semantic-release-backmerge"
    - backmergeBranches:
        - from: "main"
          to: "develop"
      message: "chore(release): backmerge ${nextRelease.version} [skip ci]"

branches:
  - main
  - name: develop
    prerelease: "beta"
  - name: release-candidate
    prerelease: "rc"
