// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/reporting/domain/repositories (interfaces: DashboardRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/dashboard_repository_mock.go -package=mocks . DashboardRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/LerianStudio/matcher/internal/reporting/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockDashboardRepository is a mock of DashboardRepository interface.
type MockDashboardRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardRepositoryMockRecorder
	isgomock struct{}
}

// MockDashboardRepositoryMockRecorder is the mock recorder for MockDashboardRepository.
type MockDashboardRepositoryMockRecorder struct {
	mock *MockDashboardRepository
}

// NewMockDashboardRepository creates a new mock instance.
func NewMockDashboardRepository(ctrl *gomock.Controller) *MockDashboardRepository {
	mock := &MockDashboardRepository{ctrl: ctrl}
	mock.recorder = &MockDashboardRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboardRepository) EXPECT() *MockDashboardRepositoryMockRecorder {
	return m.recorder
}

// GetBreakdownMetrics mocks base method.
func (m *MockDashboardRepository) GetBreakdownMetrics(ctx context.Context, filter entities.DashboardFilter) (*entities.BreakdownMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBreakdownMetrics", ctx, filter)
	ret0, _ := ret[0].(*entities.BreakdownMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBreakdownMetrics indicates an expected call of GetBreakdownMetrics.
func (mr *MockDashboardRepositoryMockRecorder) GetBreakdownMetrics(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBreakdownMetrics", reflect.TypeOf((*MockDashboardRepository)(nil).GetBreakdownMetrics), ctx, filter)
}

// GetCashImpactSummary mocks base method.
func (m *MockDashboardRepository) GetCashImpactSummary(ctx context.Context, filter entities.DashboardFilter) (*entities.CashImpactSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCashImpactSummary", ctx, filter)
	ret0, _ := ret[0].(*entities.CashImpactSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCashImpactSummary indicates an expected call of GetCashImpactSummary.
func (mr *MockDashboardRepositoryMockRecorder) GetCashImpactSummary(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCashImpactSummary", reflect.TypeOf((*MockDashboardRepository)(nil).GetCashImpactSummary), ctx, filter)
}

// GetSLAStats mocks base method.
func (m *MockDashboardRepository) GetSLAStats(ctx context.Context, filter entities.DashboardFilter) (*entities.SLAStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSLAStats", ctx, filter)
	ret0, _ := ret[0].(*entities.SLAStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSLAStats indicates an expected call of GetSLAStats.
func (mr *MockDashboardRepositoryMockRecorder) GetSLAStats(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSLAStats", reflect.TypeOf((*MockDashboardRepository)(nil).GetSLAStats), ctx, filter)
}

// GetSourceBreakdown mocks base method.
func (m *MockDashboardRepository) GetSourceBreakdown(ctx context.Context, filter entities.DashboardFilter) ([]entities.SourceBreakdown, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSourceBreakdown", ctx, filter)
	ret0, _ := ret[0].([]entities.SourceBreakdown)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSourceBreakdown indicates an expected call of GetSourceBreakdown.
func (mr *MockDashboardRepositoryMockRecorder) GetSourceBreakdown(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSourceBreakdown", reflect.TypeOf((*MockDashboardRepository)(nil).GetSourceBreakdown), ctx, filter)
}

// GetSummaryMetrics mocks base method.
func (m *MockDashboardRepository) GetSummaryMetrics(ctx context.Context, filter entities.DashboardFilter) (*entities.SummaryMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummaryMetrics", ctx, filter)
	ret0, _ := ret[0].(*entities.SummaryMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummaryMetrics indicates an expected call of GetSummaryMetrics.
func (mr *MockDashboardRepositoryMockRecorder) GetSummaryMetrics(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummaryMetrics", reflect.TypeOf((*MockDashboardRepository)(nil).GetSummaryMetrics), ctx, filter)
}

// GetTrendMetrics mocks base method.
func (m *MockDashboardRepository) GetTrendMetrics(ctx context.Context, filter entities.DashboardFilter) (*entities.TrendMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrendMetrics", ctx, filter)
	ret0, _ := ret[0].(*entities.TrendMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrendMetrics indicates an expected call of GetTrendMetrics.
func (mr *MockDashboardRepositoryMockRecorder) GetTrendMetrics(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrendMetrics", reflect.TypeOf((*MockDashboardRepository)(nil).GetTrendMetrics), ctx, filter)
}

// GetVolumeStats mocks base method.
func (m *MockDashboardRepository) GetVolumeStats(ctx context.Context, filter entities.DashboardFilter) (*entities.VolumeStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolumeStats", ctx, filter)
	ret0, _ := ret[0].(*entities.VolumeStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolumeStats indicates an expected call of GetVolumeStats.
func (mr *MockDashboardRepositoryMockRecorder) GetVolumeStats(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolumeStats", reflect.TypeOf((*MockDashboardRepository)(nil).GetVolumeStats), ctx, filter)
}
