// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/reporting/domain/repositories (interfaces: ExportJobRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/export_job_repository_mock.go -package=mocks . ExportJobRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	http "github.com/LerianStudio/lib-uncommons/v2/uncommons/net/http"
	entities "github.com/LerianStudio/matcher/internal/reporting/domain/entities"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockExportJobRepository is a mock of ExportJobRepository interface.
type MockExportJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockExportJobRepositoryMockRecorder
	isgomock struct{}
}

// MockExportJobRepositoryMockRecorder is the mock recorder for MockExportJobRepository.
type MockExportJobRepositoryMockRecorder struct {
	mock *MockExportJobRepository
}

// NewMockExportJobRepository creates a new mock instance.
func NewMockExportJobRepository(ctrl *gomock.Controller) *MockExportJobRepository {
	mock := &MockExportJobRepository{ctrl: ctrl}
	mock.recorder = &MockExportJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExportJobRepository) EXPECT() *MockExportJobRepositoryMockRecorder {
	return m.recorder
}

// ClaimNextQueued mocks base method.
func (m *MockExportJobRepository) ClaimNextQueued(ctx context.Context) (*entities.ExportJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimNextQueued", ctx)
	ret0, _ := ret[0].(*entities.ExportJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimNextQueued indicates an expected call of ClaimNextQueued.
func (mr *MockExportJobRepositoryMockRecorder) ClaimNextQueued(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimNextQueued", reflect.TypeOf((*MockExportJobRepository)(nil).ClaimNextQueued), ctx)
}

// Create mocks base method.
func (m *MockExportJobRepository) Create(ctx context.Context, job *entities.ExportJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockExportJobRepositoryMockRecorder) Create(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExportJobRepository)(nil).Create), ctx, job)
}

// Delete mocks base method.
func (m *MockExportJobRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockExportJobRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExportJobRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockExportJobRepository) GetByID(ctx context.Context, id uuid.UUID) (*entities.ExportJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.ExportJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockExportJobRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockExportJobRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockExportJobRepository) List(ctx context.Context, status *string, cursor *http.TimestampCursor, limit int) ([]*entities.ExportJob, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, status, cursor, limit)
	ret0, _ := ret[0].([]*entities.ExportJob)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockExportJobRepositoryMockRecorder) List(ctx, status, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExportJobRepository)(nil).List), ctx, status, cursor, limit)
}

// ListByContext mocks base method.
func (m *MockExportJobRepository) ListByContext(ctx context.Context, contextID uuid.UUID, limit int) ([]*entities.ExportJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByContext", ctx, contextID, limit)
	ret0, _ := ret[0].([]*entities.ExportJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByContext indicates an expected call of ListByContext.
func (mr *MockExportJobRepositoryMockRecorder) ListByContext(ctx, contextID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByContext", reflect.TypeOf((*MockExportJobRepository)(nil).ListByContext), ctx, contextID, limit)
}

// ListExpired mocks base method.
func (m *MockExportJobRepository) ListExpired(ctx context.Context, limit int) ([]*entities.ExportJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpired", ctx, limit)
	ret0, _ := ret[0].([]*entities.ExportJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpired indicates an expected call of ListExpired.
func (mr *MockExportJobRepositoryMockRecorder) ListExpired(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpired", reflect.TypeOf((*MockExportJobRepository)(nil).ListExpired), ctx, limit)
}

// RequeueForRetry mocks base method.
func (m *MockExportJobRepository) RequeueForRetry(ctx context.Context, job *entities.ExportJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequeueForRetry", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequeueForRetry indicates an expected call of RequeueForRetry.
func (mr *MockExportJobRepositoryMockRecorder) RequeueForRetry(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequeueForRetry", reflect.TypeOf((*MockExportJobRepository)(nil).RequeueForRetry), ctx, job)
}

// Update mocks base method.
func (m *MockExportJobRepository) Update(ctx context.Context, job *entities.ExportJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockExportJobRepositoryMockRecorder) Update(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExportJobRepository)(nil).Update), ctx, job)
}

// UpdateProgress mocks base method.
func (m *MockExportJobRepository) UpdateProgress(ctx context.Context, id uuid.UUID, recordsWritten, bytesWritten int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProgress", ctx, id, recordsWritten, bytesWritten)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProgress indicates an expected call of UpdateProgress.
func (mr *MockExportJobRepositoryMockRecorder) UpdateProgress(ctx, id, recordsWritten, bytesWritten any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProgress", reflect.TypeOf((*MockExportJobRepository)(nil).UpdateProgress), ctx, id, recordsWritten, bytesWritten)
}

// UpdateStatus mocks base method.
func (m *MockExportJobRepository) UpdateStatus(ctx context.Context, job *entities.ExportJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockExportJobRepositoryMockRecorder) UpdateStatus(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockExportJobRepository)(nil).UpdateStatus), ctx, job)
}
