// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/reporting/domain/repositories (interfaces: ReportRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/report_repository_mock.go -package=mocks . ReportRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	http "github.com/LerianStudio/lib-uncommons/v2/uncommons/net/http"
	entities "github.com/LerianStudio/matcher/internal/reporting/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockReportRepository is a mock of ReportRepository interface.
type MockReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepositoryMockRecorder
	isgomock struct{}
}

// MockReportRepositoryMockRecorder is the mock recorder for MockReportRepository.
type MockReportRepositoryMockRecorder struct {
	mock *MockReportRepository
}

// NewMockReportRepository creates a new mock instance.
func NewMockReportRepository(ctrl *gomock.Controller) *MockReportRepository {
	mock := &MockReportRepository{ctrl: ctrl}
	mock.recorder = &MockReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportRepository) EXPECT() *MockReportRepositoryMockRecorder {
	return m.recorder
}

// CountExceptions mocks base method.
func (m *MockReportRepository) CountExceptions(ctx context.Context, filter entities.ReportFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountExceptions", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountExceptions indicates an expected call of CountExceptions.
func (mr *MockReportRepositoryMockRecorder) CountExceptions(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountExceptions", reflect.TypeOf((*MockReportRepository)(nil).CountExceptions), ctx, filter)
}

// CountMatched mocks base method.
func (m *MockReportRepository) CountMatched(ctx context.Context, filter entities.ReportFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMatched", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMatched indicates an expected call of CountMatched.
func (mr *MockReportRepositoryMockRecorder) CountMatched(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMatched", reflect.TypeOf((*MockReportRepository)(nil).CountMatched), ctx, filter)
}

// CountTransactions mocks base method.
func (m *MockReportRepository) CountTransactions(ctx context.Context, filter entities.ReportFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTransactions", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTransactions indicates an expected call of CountTransactions.
func (mr *MockReportRepositoryMockRecorder) CountTransactions(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTransactions", reflect.TypeOf((*MockReportRepository)(nil).CountTransactions), ctx, filter)
}

// CountUnmatched mocks base method.
func (m *MockReportRepository) CountUnmatched(ctx context.Context, filter entities.ReportFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnmatched", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnmatched indicates an expected call of CountUnmatched.
func (mr *MockReportRepositoryMockRecorder) CountUnmatched(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnmatched", reflect.TypeOf((*MockReportRepository)(nil).CountUnmatched), ctx, filter)
}

// GetSummary mocks base method.
func (m *MockReportRepository) GetSummary(ctx context.Context, filter entities.ReportFilter) (*entities.SummaryReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, filter)
	ret0, _ := ret[0].(*entities.SummaryReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockReportRepositoryMockRecorder) GetSummary(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockReportRepository)(nil).GetSummary), ctx, filter)
}

// GetVarianceReport mocks base method.
func (m *MockReportRepository) GetVarianceReport(ctx context.Context, filter entities.VarianceReportFilter) ([]*entities.VarianceReportRow, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVarianceReport", ctx, filter)
	ret0, _ := ret[0].([]*entities.VarianceReportRow)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVarianceReport indicates an expected call of GetVarianceReport.
func (mr *MockReportRepositoryMockRecorder) GetVarianceReport(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVarianceReport", reflect.TypeOf((*MockReportRepository)(nil).GetVarianceReport), ctx, filter)
}

// ListMatched mocks base method.
func (m *MockReportRepository) ListMatched(ctx context.Context, filter entities.ReportFilter) ([]*entities.MatchedItem, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMatched", ctx, filter)
	ret0, _ := ret[0].([]*entities.MatchedItem)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMatched indicates an expected call of ListMatched.
func (mr *MockReportRepositoryMockRecorder) ListMatched(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMatched", reflect.TypeOf((*MockReportRepository)(nil).ListMatched), ctx, filter)
}

// ListMatchedForExport mocks base method.
func (m *MockReportRepository) ListMatchedForExport(ctx context.Context, filter entities.ReportFilter, maxRecords int) ([]*entities.MatchedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMatchedForExport", ctx, filter, maxRecords)
	ret0, _ := ret[0].([]*entities.MatchedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMatchedForExport indicates an expected call of ListMatchedForExport.
func (mr *MockReportRepositoryMockRecorder) ListMatchedForExport(ctx, filter, maxRecords any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMatchedForExport", reflect.TypeOf((*MockReportRepository)(nil).ListMatchedForExport), ctx, filter, maxRecords)
}

// ListMatchedPage mocks base method.
func (m *MockReportRepository) ListMatchedPage(ctx context.Context, filter entities.ReportFilter, afterKey string, limit int) ([]*entities.MatchedItem, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMatchedPage", ctx, filter, afterKey, limit)
	ret0, _ := ret[0].([]*entities.MatchedItem)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMatchedPage indicates an expected call of ListMatchedPage.
func (mr *MockReportRepositoryMockRecorder) ListMatchedPage(ctx, filter, afterKey, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMatchedPage", reflect.TypeOf((*MockReportRepository)(nil).ListMatchedPage), ctx, filter, afterKey, limit)
}

// ListUnmatched mocks base method.
func (m *MockReportRepository) ListUnmatched(ctx context.Context, filter entities.ReportFilter) ([]*entities.UnmatchedItem, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnmatched", ctx, filter)
	ret0, _ := ret[0].([]*entities.UnmatchedItem)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUnmatched indicates an expected call of ListUnmatched.
func (mr *MockReportRepositoryMockRecorder) ListUnmatched(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnmatched", reflect.TypeOf((*MockReportRepository)(nil).ListUnmatched), ctx, filter)
}

// ListUnmatchedForExport mocks base method.
func (m *MockReportRepository) ListUnmatchedForExport(ctx context.Context, filter entities.ReportFilter, maxRecords int) ([]*entities.UnmatchedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnmatchedForExport", ctx, filter, maxRecords)
	ret0, _ := ret[0].([]*entities.UnmatchedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnmatchedForExport indicates an expected call of ListUnmatchedForExport.
func (mr *MockReportRepositoryMockRecorder) ListUnmatchedForExport(ctx, filter, maxRecords any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnmatchedForExport", reflect.TypeOf((*MockReportRepository)(nil).ListUnmatchedForExport), ctx, filter, maxRecords)
}

// ListUnmatchedPage mocks base method.
func (m *MockReportRepository) ListUnmatchedPage(ctx context.Context, filter entities.ReportFilter, afterKey string, limit int) ([]*entities.UnmatchedItem, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnmatchedPage", ctx, filter, afterKey, limit)
	ret0, _ := ret[0].([]*entities.UnmatchedItem)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUnmatchedPage indicates an expected call of ListUnmatchedPage.
func (mr *MockReportRepositoryMockRecorder) ListUnmatchedPage(ctx, filter, afterKey, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnmatchedPage", reflect.TypeOf((*MockReportRepository)(nil).ListUnmatchedPage), ctx, filter, afterKey, limit)
}

// ListVarianceForExport mocks base method.
func (m *MockReportRepository) ListVarianceForExport(ctx context.Context, filter entities.VarianceReportFilter, maxRecords int) ([]*entities.VarianceReportRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVarianceForExport", ctx, filter, maxRecords)
	ret0, _ := ret[0].([]*entities.VarianceReportRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVarianceForExport indicates an expected call of ListVarianceForExport.
func (mr *MockReportRepositoryMockRecorder) ListVarianceForExport(ctx, filter, maxRecords any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVarianceForExport", reflect.TypeOf((*MockReportRepository)(nil).ListVarianceForExport), ctx, filter, maxRecords)
}

// ListVariancePage mocks base method.
func (m *MockReportRepository) ListVariancePage(ctx context.Context, filter entities.VarianceReportFilter, afterKey string, limit int) ([]*entities.VarianceReportRow, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVariancePage", ctx, filter, afterKey, limit)
	ret0, _ := ret[0].([]*entities.VarianceReportRow)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListVariancePage indicates an expected call of ListVariancePage.
func (mr *MockReportRepositoryMockRecorder) ListVariancePage(ctx, filter, afterKey, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVariancePage", reflect.TypeOf((*MockReportRepository)(nil).ListVariancePage), ctx, filter, afterKey, limit)
}
