// Copyright 2025 Lerian Studio. All rights reserved.
// Use of this source code is governed by an Elastic License 2.0
// that can be found in the LICENSE.md file.

//go:build unit

package command

import (
	"context"
	"errors"
	"io"
	"strings"
	"testing"

	sharedPorts "github.com/LerianStudio/matcher/internal/shared/ports"

	"github.com/google/uuid"

	"github.com/LerianStudio/matcher/internal/ingestion/domain/entities"
	"github.com/LerianStudio/matcher/internal/ingestion/ports"
	shared "github.com/LerianStudio/matcher/internal/shared/domain"
)

// errFuzzStubUnsupportedFormat is the sentinel returned by fuzzStubParser
// when the fuzzed format is not in its allow-list. A static sentinel keeps
// err113 happy and, more importantly, gives the fuzz body something stable
// to ignore — we only care about sentinels from the production code.
var errFuzzStubUnsupportedFormat = errors.New("fuzz stub: unsupported format")

// maxFuzzFormatBytes bounds fuzz-generated Format strings. The production
// validator lowercases and trims, which are O(n) in the input length;
// capping at 8KB keeps the fuzzer productive without starving iterations
// on pathological multi-megabyte strings generated by the corpus engine.
const maxFuzzFormatBytes = 8 * 1024

// fuzzStubParser is the minimal ParserRegistry implementation the fuzz
// target needs. It claims to recognise only the lowercase-trimmed variants
// of csv/json/xml — the real registry maintains a larger table but the
// property we care about here is purely about error-shape invariants, not
// the exact supported-format matrix.
type fuzzStubParser struct{}

// fuzzStubAcceptedParser is a non-nil sentinel Parser returned for accepted
// formats so the (nil, nil) return pair (flagged by nilnil) is avoided. It
// is never called: validateTrustedStreamInput only checks the error return.
type fuzzStubAcceptedParser struct{}

func (fuzzStubAcceptedParser) Parse(
	_ context.Context,
	_ io.Reader,
	_ *entities.IngestionJob,
	_ *shared.FieldMap,
) (*ports.ParseResult, error) {
	return nil, errFuzzStubUnsupportedFormat
}

func (fuzzStubAcceptedParser) SupportedFormat() string { return "fuzz-stub" }

func (fuzzStubParser) GetParser(format string) (ports.Parser, error) {
	switch format {
	case "csv", "json", "xml":
		return fuzzStubAcceptedParser{}, nil
	default:
		return nil, errFuzzStubUnsupportedFormat
	}
}

func (fuzzStubParser) Register(_ ports.Parser) {}

// FuzzTrustedStreamFormat drives validateTrustedStreamInput with arbitrary
// Format strings while holding the other required fields constant at their
// valid values. The invariants verified are:
//
//  1. Never panics for any byte input — including control chars, null bytes,
//     extremely long strings, and path-traversal payloads.
//  2. Always returns either nil (the stub registry accepts the format) or
//     one of the documented validation sentinels.
//  3. Never returns an error mid-pipeline — validation is synchronous and
//     pure; infrastructure is never touched before this check.
func FuzzTrustedStreamFormat(f *testing.F) {
	// Canonical supported formats (lowercase, no whitespace).
	f.Add("csv")
	f.Add("json")
	f.Add("xml")

	// Empty and whitespace-only — must trigger ErrIngestFromTrustedStreamFormatRequired.
	f.Add("")
	f.Add("   ")
	f.Add("\t\n ")

	// Case handling: validator lowercases, so uppercase should normalize.
	f.Add("CSV")
	f.Add("Json")

	// Security-flavoured payloads — path traversal, SQL, null bytes.
	f.Add("../../etc/passwd")
	f.Add("'; DROP TABLE sources;--")
	f.Add("\x00\x01\x02")

	// Boundary: very long but within the cap, plus unicode.
	f.Add(strings.Repeat("a", 10000))
	f.Add("\u00e9\u00e7\u00e3o")

	// Build the UseCase skeleton once — only the parsers field is touched
	// by validateTrustedStreamInput, so constructing through NewUseCase
	// (which demands a fully-wired dep graph) is unnecessary here.
	uc := &UseCase{parsers: fuzzStubParser{}}

	// Constant valid field values. Format is the only fuzzed dimension.
	contextID := uuid.New()
	sourceID := uuid.New()
	content := io.NopCloser(strings.NewReader("fuzz-body"))

	f.Fuzz(func(t *testing.T, format string) {
		if len(format) > maxFuzzFormatBytes {
			format = format[:maxFuzzFormatBytes]
		}

		input := sharedPorts.TrustedContentInput{
			ContextID: contextID,
			SourceID:  sourceID,
			Format:    format,
			Content:   content,
		}

		err := validateTrustedStreamInput(uc, input)
		if err == nil {
			// Nil error is legal only when the stub registry accepted the
			// trimmed/lowercased format. Anything else is a contract bug.
			normalized := strings.ToLower(strings.TrimSpace(format))

			switch normalized {
			case "csv", "json", "xml":
				return
			default:
				t.Fatalf(
					"validator returned nil for unsupported format %q (normalized=%q)",
					format, normalized,
				)
			}
		}

		// Non-nil error path: it MUST match one of the documented sentinels.
		// Any other error shape means validation leaked an undocumented
		// failure mode into the trusted-stream intake contract.
		switch {
		case errors.Is(err, ErrIngestFromTrustedStreamFormatRequired):
		case errors.Is(err, ErrIngestFromTrustedStreamFormatUnsupported):
		default:
			t.Fatalf(
				"validator returned undocumented error for format %q: %v",
				format, err,
			)
		}
	})
}
