// Code generated by MockGen. DO NOT EDIT.
// Source: context_repository.go
//
// Generated by this command:
//
//	mockgen -source=context_repository.go -destination=mocks/context_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	http "github.com/LerianStudio/lib-commons/v4/commons/net/http"
	entities "github.com/LerianStudio/matcher/internal/configuration/domain/entities"
	value_objects "github.com/LerianStudio/matcher/internal/configuration/domain/value_objects"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockContextRepository is a mock of ContextRepository interface.
type MockContextRepository struct {
	ctrl     *gomock.Controller
	recorder *MockContextRepositoryMockRecorder
	isgomock struct{}
}

// MockContextRepositoryMockRecorder is the mock recorder for MockContextRepository.
type MockContextRepositoryMockRecorder struct {
	mock *MockContextRepository
}

// NewMockContextRepository creates a new mock instance.
func NewMockContextRepository(ctrl *gomock.Controller) *MockContextRepository {
	mock := &MockContextRepository{ctrl: ctrl}
	mock.recorder = &MockContextRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextRepository) EXPECT() *MockContextRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockContextRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockContextRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockContextRepository)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockContextRepository) Create(ctx context.Context, entity *entities.ReconciliationContext) (*entities.ReconciliationContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*entities.ReconciliationContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockContextRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockContextRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockContextRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockContextRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockContextRepository)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockContextRepository) FindAll(ctx context.Context, cursor string, limit int, contextType *value_objects.ContextType, status *value_objects.ContextStatus) ([]*entities.ReconciliationContext, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, cursor, limit, contextType, status)
	ret0, _ := ret[0].([]*entities.ReconciliationContext)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockContextRepositoryMockRecorder) FindAll(ctx, cursor, limit, contextType, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockContextRepository)(nil).FindAll), ctx, cursor, limit, contextType, status)
}

// FindByID mocks base method.
func (m *MockContextRepository) FindByID(ctx context.Context, id uuid.UUID) (*entities.ReconciliationContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entities.ReconciliationContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockContextRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockContextRepository)(nil).FindByID), ctx, id)
}

// FindByName mocks base method.
func (m *MockContextRepository) FindByName(ctx context.Context, name string) (*entities.ReconciliationContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*entities.ReconciliationContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockContextRepositoryMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockContextRepository)(nil).FindByName), ctx, name)
}

// Update mocks base method.
func (m *MockContextRepository) Update(ctx context.Context, entity *entities.ReconciliationContext) (*entities.ReconciliationContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(*entities.ReconciliationContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockContextRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockContextRepository)(nil).Update), ctx, entity)
}
