// Code generated by MockGen. DO NOT EDIT.
// Source: fee_rule_repository.go
//
// Generated by this command:
//
//	mockgen -source=fee_rule_repository.go -destination=mocks/fee_rule_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	fee "github.com/LerianStudio/matcher/internal/shared/domain/fee"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFeeRuleRepository is a mock of FeeRuleRepository interface.
type MockFeeRuleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeeRuleRepositoryMockRecorder
	isgomock struct{}
}

// MockFeeRuleRepositoryMockRecorder is the mock recorder for MockFeeRuleRepository.
type MockFeeRuleRepositoryMockRecorder struct {
	mock *MockFeeRuleRepository
}

// NewMockFeeRuleRepository creates a new mock instance.
func NewMockFeeRuleRepository(ctrl *gomock.Controller) *MockFeeRuleRepository {
	mock := &MockFeeRuleRepository{ctrl: ctrl}
	mock.recorder = &MockFeeRuleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeeRuleRepository) EXPECT() *MockFeeRuleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFeeRuleRepository) Create(ctx context.Context, rule *fee.FeeRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFeeRuleRepositoryMockRecorder) Create(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeeRuleRepository)(nil).Create), ctx, rule)
}

// CreateWithTx mocks base method.
func (m *MockFeeRuleRepository) CreateWithTx(ctx context.Context, tx *sql.Tx, rule *fee.FeeRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, tx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockFeeRuleRepositoryMockRecorder) CreateWithTx(ctx, tx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockFeeRuleRepository)(nil).CreateWithTx), ctx, tx, rule)
}

// Delete mocks base method.
func (m *MockFeeRuleRepository) Delete(ctx context.Context, contextID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, contextID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFeeRuleRepositoryMockRecorder) Delete(ctx, contextID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFeeRuleRepository)(nil).Delete), ctx, contextID, id)
}

// DeleteWithTx mocks base method.
func (m *MockFeeRuleRepository) DeleteWithTx(ctx context.Context, tx *sql.Tx, contextID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithTx", ctx, tx, contextID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWithTx indicates an expected call of DeleteWithTx.
func (mr *MockFeeRuleRepositoryMockRecorder) DeleteWithTx(ctx, tx, contextID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithTx", reflect.TypeOf((*MockFeeRuleRepository)(nil).DeleteWithTx), ctx, tx, contextID, id)
}

// FindByContextID mocks base method.
func (m *MockFeeRuleRepository) FindByContextID(ctx context.Context, contextID uuid.UUID) ([]*fee.FeeRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByContextID", ctx, contextID)
	ret0, _ := ret[0].([]*fee.FeeRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByContextID indicates an expected call of FindByContextID.
func (mr *MockFeeRuleRepositoryMockRecorder) FindByContextID(ctx, contextID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByContextID", reflect.TypeOf((*MockFeeRuleRepository)(nil).FindByContextID), ctx, contextID)
}

// FindByID mocks base method.
func (m *MockFeeRuleRepository) FindByID(ctx context.Context, id uuid.UUID) (*fee.FeeRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*fee.FeeRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFeeRuleRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFeeRuleRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockFeeRuleRepository) Update(ctx context.Context, rule *fee.FeeRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFeeRuleRepositoryMockRecorder) Update(ctx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFeeRuleRepository)(nil).Update), ctx, rule)
}

// UpdateWithTx mocks base method.
func (m *MockFeeRuleRepository) UpdateWithTx(ctx context.Context, tx *sql.Tx, rule *fee.FeeRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithTx", ctx, tx, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithTx indicates an expected call of UpdateWithTx.
func (mr *MockFeeRuleRepositoryMockRecorder) UpdateWithTx(ctx, tx, rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithTx", reflect.TypeOf((*MockFeeRuleRepository)(nil).UpdateWithTx), ctx, tx, rule)
}
