// Code generated by MockGen. DO NOT EDIT.
// Source: field_map_repository.go
//
// Generated by this command:
//
//	mockgen -source=field_map_repository.go -destination=mocks/field_map_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	shared "github.com/LerianStudio/matcher/internal/shared/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockFieldMapRepository is a mock of FieldMapRepository interface.
type MockFieldMapRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFieldMapRepositoryMockRecorder
	isgomock struct{}
}

// MockFieldMapRepositoryMockRecorder is the mock recorder for MockFieldMapRepository.
type MockFieldMapRepositoryMockRecorder struct {
	mock *MockFieldMapRepository
}

// NewMockFieldMapRepository creates a new mock instance.
func NewMockFieldMapRepository(ctrl *gomock.Controller) *MockFieldMapRepository {
	mock := &MockFieldMapRepository{ctrl: ctrl}
	mock.recorder = &MockFieldMapRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFieldMapRepository) EXPECT() *MockFieldMapRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFieldMapRepository) Create(ctx context.Context, entity *shared.FieldMap) (*shared.FieldMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*shared.FieldMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFieldMapRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFieldMapRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockFieldMapRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFieldMapRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFieldMapRepository)(nil).Delete), ctx, id)
}

// ExistsBySourceIDs mocks base method.
func (m *MockFieldMapRepository) ExistsBySourceIDs(ctx context.Context, sourceIDs []uuid.UUID) (map[uuid.UUID]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsBySourceIDs", ctx, sourceIDs)
	ret0, _ := ret[0].(map[uuid.UUID]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsBySourceIDs indicates an expected call of ExistsBySourceIDs.
func (mr *MockFieldMapRepositoryMockRecorder) ExistsBySourceIDs(ctx, sourceIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsBySourceIDs", reflect.TypeOf((*MockFieldMapRepository)(nil).ExistsBySourceIDs), ctx, sourceIDs)
}

// FindByID mocks base method.
func (m *MockFieldMapRepository) FindByID(ctx context.Context, id uuid.UUID) (*shared.FieldMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*shared.FieldMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockFieldMapRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockFieldMapRepository)(nil).FindByID), ctx, id)
}

// FindBySourceID mocks base method.
func (m *MockFieldMapRepository) FindBySourceID(ctx context.Context, sourceID uuid.UUID) (*shared.FieldMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySourceID", ctx, sourceID)
	ret0, _ := ret[0].(*shared.FieldMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySourceID indicates an expected call of FindBySourceID.
func (mr *MockFieldMapRepositoryMockRecorder) FindBySourceID(ctx, sourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySourceID", reflect.TypeOf((*MockFieldMapRepository)(nil).FindBySourceID), ctx, sourceID)
}

// Update mocks base method.
func (m *MockFieldMapRepository) Update(ctx context.Context, entity *shared.FieldMap) (*shared.FieldMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(*shared.FieldMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFieldMapRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFieldMapRepository)(nil).Update), ctx, entity)
}
