// Code generated by MockGen. DO NOT EDIT.
// Source: match_rule_repository.go
//
// Generated by this command:
//
//	mockgen -source=match_rule_repository.go -destination=mocks/match_rule_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	http "github.com/LerianStudio/lib-uncommons/v2/uncommons/net/http"
	entities "github.com/LerianStudio/matcher/internal/configuration/domain/entities"
	value_objects "github.com/LerianStudio/matcher/internal/configuration/domain/value_objects"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchRuleRepository is a mock of MatchRuleRepository interface.
type MockMatchRuleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMatchRuleRepositoryMockRecorder
	isgomock struct{}
}

// MockMatchRuleRepositoryMockRecorder is the mock recorder for MockMatchRuleRepository.
type MockMatchRuleRepositoryMockRecorder struct {
	mock *MockMatchRuleRepository
}

// NewMockMatchRuleRepository creates a new mock instance.
func NewMockMatchRuleRepository(ctrl *gomock.Controller) *MockMatchRuleRepository {
	mock := &MockMatchRuleRepository{ctrl: ctrl}
	mock.recorder = &MockMatchRuleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchRuleRepository) EXPECT() *MockMatchRuleRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMatchRuleRepository) Create(ctx context.Context, entity *entities.MatchRule) (*entities.MatchRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*entities.MatchRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMatchRuleRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMatchRuleRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockMatchRuleRepository) Delete(ctx context.Context, contextID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, contextID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMatchRuleRepositoryMockRecorder) Delete(ctx, contextID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMatchRuleRepository)(nil).Delete), ctx, contextID, id)
}

// FindByContextID mocks base method.
func (m *MockMatchRuleRepository) FindByContextID(ctx context.Context, contextID uuid.UUID, cursor string, limit int) (entities.MatchRules, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByContextID", ctx, contextID, cursor, limit)
	ret0, _ := ret[0].(entities.MatchRules)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByContextID indicates an expected call of FindByContextID.
func (mr *MockMatchRuleRepositoryMockRecorder) FindByContextID(ctx, contextID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByContextID", reflect.TypeOf((*MockMatchRuleRepository)(nil).FindByContextID), ctx, contextID, cursor, limit)
}

// FindByContextIDAndType mocks base method.
func (m *MockMatchRuleRepository) FindByContextIDAndType(ctx context.Context, contextID uuid.UUID, ruleType value_objects.RuleType, cursor string, limit int) (entities.MatchRules, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByContextIDAndType", ctx, contextID, ruleType, cursor, limit)
	ret0, _ := ret[0].(entities.MatchRules)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByContextIDAndType indicates an expected call of FindByContextIDAndType.
func (mr *MockMatchRuleRepositoryMockRecorder) FindByContextIDAndType(ctx, contextID, ruleType, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByContextIDAndType", reflect.TypeOf((*MockMatchRuleRepository)(nil).FindByContextIDAndType), ctx, contextID, ruleType, cursor, limit)
}

// FindByID mocks base method.
func (m *MockMatchRuleRepository) FindByID(ctx context.Context, contextID, id uuid.UUID) (*entities.MatchRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, contextID, id)
	ret0, _ := ret[0].(*entities.MatchRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMatchRuleRepositoryMockRecorder) FindByID(ctx, contextID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMatchRuleRepository)(nil).FindByID), ctx, contextID, id)
}

// FindByPriority mocks base method.
func (m *MockMatchRuleRepository) FindByPriority(ctx context.Context, contextID uuid.UUID, priority int) (*entities.MatchRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPriority", ctx, contextID, priority)
	ret0, _ := ret[0].(*entities.MatchRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPriority indicates an expected call of FindByPriority.
func (mr *MockMatchRuleRepositoryMockRecorder) FindByPriority(ctx, contextID, priority any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPriority", reflect.TypeOf((*MockMatchRuleRepository)(nil).FindByPriority), ctx, contextID, priority)
}

// ReorderPriorities mocks base method.
func (m *MockMatchRuleRepository) ReorderPriorities(ctx context.Context, contextID uuid.UUID, ruleIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReorderPriorities", ctx, contextID, ruleIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReorderPriorities indicates an expected call of ReorderPriorities.
func (mr *MockMatchRuleRepositoryMockRecorder) ReorderPriorities(ctx, contextID, ruleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReorderPriorities", reflect.TypeOf((*MockMatchRuleRepository)(nil).ReorderPriorities), ctx, contextID, ruleIDs)
}

// Update mocks base method.
func (m *MockMatchRuleRepository) Update(ctx context.Context, entity *entities.MatchRule) (*entities.MatchRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(*entities.MatchRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMatchRuleRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMatchRuleRepository)(nil).Update), ctx, entity)
}
