// Code generated by MockGen. DO NOT EDIT.
// Source: source_repository.go
//
// Generated by this command:
//
//	mockgen -source=source_repository.go -destination=mocks/mock_source_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	http "github.com/LerianStudio/lib-uncommons/v2/uncommons/net/http"
	entities "github.com/LerianStudio/matcher/internal/configuration/domain/entities"
	value_objects "github.com/LerianStudio/matcher/internal/configuration/domain/value_objects"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSourceRepository is a mock of SourceRepository interface.
type MockSourceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSourceRepositoryMockRecorder
	isgomock struct{}
}

// MockSourceRepositoryMockRecorder is the mock recorder for MockSourceRepository.
type MockSourceRepositoryMockRecorder struct {
	mock *MockSourceRepository
}

// NewMockSourceRepository creates a new mock instance.
func NewMockSourceRepository(ctrl *gomock.Controller) *MockSourceRepository {
	mock := &MockSourceRepository{ctrl: ctrl}
	mock.recorder = &MockSourceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceRepository) EXPECT() *MockSourceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSourceRepository) Create(ctx context.Context, entity *entities.ReconciliationSource) (*entities.ReconciliationSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*entities.ReconciliationSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSourceRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSourceRepository)(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockSourceRepository) Delete(ctx context.Context, contextID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, contextID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSourceRepositoryMockRecorder) Delete(ctx, contextID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSourceRepository)(nil).Delete), ctx, contextID, id)
}

// FindByContextID mocks base method.
func (m *MockSourceRepository) FindByContextID(ctx context.Context, contextID uuid.UUID, cursor string, limit int) ([]*entities.ReconciliationSource, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByContextID", ctx, contextID, cursor, limit)
	ret0, _ := ret[0].([]*entities.ReconciliationSource)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByContextID indicates an expected call of FindByContextID.
func (mr *MockSourceRepositoryMockRecorder) FindByContextID(ctx, contextID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByContextID", reflect.TypeOf((*MockSourceRepository)(nil).FindByContextID), ctx, contextID, cursor, limit)
}

// FindByContextIDAndType mocks base method.
func (m *MockSourceRepository) FindByContextIDAndType(ctx context.Context, contextID uuid.UUID, sourceType value_objects.SourceType, cursor string, limit int) ([]*entities.ReconciliationSource, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByContextIDAndType", ctx, contextID, sourceType, cursor, limit)
	ret0, _ := ret[0].([]*entities.ReconciliationSource)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByContextIDAndType indicates an expected call of FindByContextIDAndType.
func (mr *MockSourceRepositoryMockRecorder) FindByContextIDAndType(ctx, contextID, sourceType, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByContextIDAndType", reflect.TypeOf((*MockSourceRepository)(nil).FindByContextIDAndType), ctx, contextID, sourceType, cursor, limit)
}

// FindByID mocks base method.
func (m *MockSourceRepository) FindByID(ctx context.Context, contextID, id uuid.UUID) (*entities.ReconciliationSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, contextID, id)
	ret0, _ := ret[0].(*entities.ReconciliationSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSourceRepositoryMockRecorder) FindByID(ctx, contextID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSourceRepository)(nil).FindByID), ctx, contextID, id)
}

// Update mocks base method.
func (m *MockSourceRepository) Update(ctx context.Context, entity *entities.ReconciliationSource) (*entities.ReconciliationSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(*entities.ReconciliationSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSourceRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSourceRepository)(nil).Update), ctx, entity)
}
