// Copyright 2025 Lerian Studio. All rights reserved.
// Use of this source code is governed by an Elastic License 2.0
// that can be found in the LICENSE.md file.

package bootstrap

import "github.com/LerianStudio/lib-commons/v4/commons/systemplane/domain"

func matcherKeyDefsRedisRabbitMQ() []domain.KeyDef {
	return concatKeyDefs(
		matcherKeyDefsRedisCore(),
		matcherKeyDefsRedisRuntime(),
		matcherKeyDefsRabbitMQConnection(),
		matcherKeyDefsRabbitMQHealth(),
	)
}

func matcherKeyDefsRedisCore() []domain.KeyDef {
	return []domain.KeyDef{
		// --- Redis. ---
		{
			Key:              "redis.host",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRedisHost,
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Redis host address(es), comma-separated for sentinel mode",
			Group:            "redis",
			Component:        "redis",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "redis.master_name",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     "",
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Redis sentinel master name (enables sentinel mode when set)",
			Group:            "redis",
			Component:        "redis",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "redis.password",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     "",
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Secret:           true,
			Description:      "Redis connection password",
			Group:            "redis",
			Component:        "redis",
			RedactPolicy:     domain.RedactFull,
		},
		{
			Key:              "redis.db",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRedisDB,
			ValueType:        domain.ValueTypeInt,
			Validator:        validateNonNegativeInt,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Redis database number",
			Group:            "redis",
			Component:        "redis",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "redis.protocol",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRedisProtocol,
			ValueType:        domain.ValueTypeInt,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Redis protocol version (2 or 3)",
			Group:            "redis",
			Component:        "redis",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "redis.tls",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRedisTLS,
			ValueType:        domain.ValueTypeBool,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Enable TLS for Redis connections",
			Group:            "redis",
			Component:        "redis",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "redis.ca_cert",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     "",
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Secret:           true,
			Description:      "Redis TLS CA certificate content",
			Group:            "redis",
			Component:        "redis",
			RedactPolicy:     domain.RedactFull,
		},
	}
}

func matcherKeyDefsRedisRuntime() []domain.KeyDef {
	return []domain.KeyDef{
		{
			Key:              "redis.pool_size",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRedisPoolSize,
			ValueType:        domain.ValueTypeInt,
			Validator:        validatePositiveInt,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Redis connection pool size",
			Group:            "redis",
			Component:        "redis",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "redis.min_idle_conn",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRedisMinIdleConn,
			ValueType:        domain.ValueTypeInt,
			Validator:        validateNonNegativeInt,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Minimum number of idle Redis connections",
			Group:            "redis",
			Component:        "redis",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "redis.read_timeout_ms",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRedisReadTimeout,
			ValueType:        domain.ValueTypeInt,
			Validator:        validatePositiveInt,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Redis read timeout in milliseconds",
			Group:            "redis",
			Component:        "redis",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "redis.write_timeout_ms",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRedisWriteTimeout,
			ValueType:        domain.ValueTypeInt,
			Validator:        validatePositiveInt,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Redis write timeout in milliseconds",
			Group:            "redis",
			Component:        "redis",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "redis.dial_timeout_ms",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRedisDialTimeout,
			ValueType:        domain.ValueTypeInt,
			Validator:        validatePositiveInt,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Redis dial timeout in milliseconds",
			Group:            "redis",
			Component:        "redis",
			RedactPolicy:     domain.RedactNone,
		},
	}
}

func matcherKeyDefsRabbitMQConnection() []domain.KeyDef {
	return []domain.KeyDef{
		// --- RabbitMQ. ---
		{
			Key:              "rabbitmq.uri",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRabbitURI,
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "RabbitMQ connection URI scheme",
			Group:            "rabbitmq",
			Component:        "rabbitmq",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "rabbitmq.host",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRabbitHost,
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "RabbitMQ host address",
			Group:            "rabbitmq",
			Component:        "rabbitmq",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "rabbitmq.port",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRabbitPort,
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "RabbitMQ port number",
			Group:            "rabbitmq",
			Component:        "rabbitmq",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "rabbitmq.user",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRabbitUser,
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "RabbitMQ connection user",
			Group:            "rabbitmq",
			Component:        "rabbitmq",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "rabbitmq.password",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRabbitPassword,
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Secret:           true,
			Description:      "RabbitMQ connection password",
			Group:            "rabbitmq",
			Component:        "rabbitmq",
			RedactPolicy:     domain.RedactFull,
		},
		{
			Key:              "rabbitmq.vhost",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRabbitVHost,
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "RabbitMQ virtual host",
			Group:            "rabbitmq",
			Component:        "rabbitmq",
			RedactPolicy:     domain.RedactNone,
		},
	}
}

func matcherKeyDefsRabbitMQHealth() []domain.KeyDef {
	return []domain.KeyDef{
		{
			Key:              "rabbitmq.health_url",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRabbitHealthURL,
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "RabbitMQ management API health endpoint URL",
			Group:            "rabbitmq",
			Component:        "rabbitmq",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "rabbitmq.allow_insecure_health_check",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultRabbitAllowInsecureHealth,
			ValueType:        domain.ValueTypeBool,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Allow insecure TLS for RabbitMQ health checks",
			Group:            "rabbitmq",
			Component:        "rabbitmq",
			RedactPolicy:     domain.RedactNone,
		},
	}
}
