// Copyright 2025 Lerian Studio. All rights reserved.
// Use of this source code is governed by an Elastic License 2.0
// that can be found in the LICENSE.md file.

package bootstrap

import "github.com/LerianStudio/matcher/pkg/systemplane/domain"

func matcherKeyDefsPostgres() []domain.KeyDef {
	return concatKeyDefs(
		matcherKeyDefsPostgresPrimary(),
		matcherKeyDefsPostgresReplica(),
		matcherKeyDefsPostgresPooling(),
		matcherKeyDefsPostgresOperations(),
	)
}

func matcherKeyDefsPostgresPrimary() []domain.KeyDef {
	return []domain.KeyDef{
		// --- PostgreSQL. ---
		{
			Key:              "postgres.primary_host",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultPGHost,
			ValueType:        domain.ValueTypeString,
			Validator:        validateNonEmptyString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "PostgreSQL primary host address",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "postgres.primary_port",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultPGPort,
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "PostgreSQL primary port",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "postgres.primary_user",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultPGUser,
			ValueType:        domain.ValueTypeString,
			Validator:        validateNonEmptyString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "PostgreSQL primary connection user",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "postgres.primary_password",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultPGPassword,
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Secret:           true,
			Description:      "PostgreSQL primary connection password",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactFull,
		},
		{
			Key:              "postgres.primary_db",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultPGDB,
			ValueType:        domain.ValueTypeString,
			Validator:        validateNonEmptyString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "PostgreSQL primary database name",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "postgres.primary_ssl_mode",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultPGSSLMode,
			ValueType:        domain.ValueTypeString,
			Validator:        validateSSLMode,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "PostgreSQL primary SSL mode (disable, require, verify-ca, verify-full)",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
	}
}

func matcherKeyDefsPostgresReplica() []domain.KeyDef {
	return []domain.KeyDef{
		{
			Key:              "postgres.replica_host",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     "",
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "PostgreSQL replica host address",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "postgres.replica_port",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     "",
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "PostgreSQL replica port",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "postgres.replica_user",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     "",
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "PostgreSQL replica connection user",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "postgres.replica_password",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     "",
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Secret:           true,
			Description:      "PostgreSQL replica connection password",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactFull,
		},
		{
			Key:              "postgres.replica_db",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     "",
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "PostgreSQL replica database name",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "postgres.replica_ssl_mode",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     "",
			ValueType:        domain.ValueTypeString,
			Validator:        validateOptionalSSLMode,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "PostgreSQL replica SSL mode (disable, require, verify-ca, verify-full)",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
	}
}

func matcherKeyDefsPostgresPooling() []domain.KeyDef {
	return []domain.KeyDef{
		{
			Key:              "postgres.max_open_connections",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultPGMaxOpenConns,
			ValueType:        domain.ValueTypeInt,
			Validator:        validatePositiveInt,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Maximum number of open PostgreSQL connections",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "postgres.max_idle_connections",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultPGMaxIdleConns,
			ValueType:        domain.ValueTypeInt,
			Validator:        validatePositiveInt,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Maximum number of idle PostgreSQL connections",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "postgres.conn_max_lifetime_mins",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultPGConnMaxLifeMins,
			ValueType:        domain.ValueTypeInt,
			Validator:        validatePositiveInt,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Maximum connection lifetime in minutes",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "postgres.conn_max_idle_time_mins",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultPGConnMaxIdleMins,
			ValueType:        domain.ValueTypeInt,
			Validator:        validatePositiveInt,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Maximum idle connection time in minutes",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "postgres.connect_timeout_sec",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultPGConnectTimeout,
			ValueType:        domain.ValueTypeInt,
			Validator:        validatePositiveInt,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "PostgreSQL connection timeout in seconds",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
		{
			Key:              "postgres.query_timeout_sec",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultPGQueryTimeout,
			ValueType:        domain.ValueTypeInt,
			Validator:        validatePositiveInt,
			ApplyBehavior:    domain.ApplyLiveRead,
			MutableAtRuntime: true,
			Description:      "PostgreSQL query timeout in seconds",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
	}
}

func matcherKeyDefsPostgresOperations() []domain.KeyDef {
	return []domain.KeyDef{
		{
			Key:              "postgres.migrations_path",
			Kind:             domain.KindConfig,
			AllowedScopes:    []domain.Scope{domain.ScopeGlobal},
			DefaultValue:     defaultPGMigrationsPath,
			ValueType:        domain.ValueTypeString,
			ApplyBehavior:    domain.ApplyBundleRebuild,
			MutableAtRuntime: true,
			Description:      "Path to database migration files",
			Group:            "postgres",
			Component:        "postgres",
			RedactPolicy:     domain.RedactNone,
		},
	}
}
