// Code generated by MockGen. DO NOT EDIT.
// Source: internal/shared/objectstorage/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/shared/objectstorage/client.go -destination=internal/shared/objectstorage/mocks/backend_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	ports "github.com/LerianStudio/matcher/internal/shared/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockBackend) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBackendMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBackend)(nil).Delete), ctx, key)
}

// Download mocks base method.
func (m *MockBackend) Download(ctx context.Context, key string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockBackendMockRecorder) Download(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockBackend)(nil).Download), ctx, key)
}

// Exists mocks base method.
func (m *MockBackend) Exists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockBackendMockRecorder) Exists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockBackend)(nil).Exists), ctx, key)
}

// GeneratePresignedURL mocks base method.
func (m *MockBackend) GeneratePresignedURL(ctx context.Context, key string, expiry time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedURL", ctx, key, expiry)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePresignedURL indicates an expected call of GeneratePresignedURL.
func (mr *MockBackendMockRecorder) GeneratePresignedURL(ctx, key, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedURL", reflect.TypeOf((*MockBackend)(nil).GeneratePresignedURL), ctx, key, expiry)
}

// Upload mocks base method.
func (m *MockBackend) Upload(ctx context.Context, key string, reader io.Reader, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, key, reader, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockBackendMockRecorder) Upload(ctx, key, reader, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockBackend)(nil).Upload), ctx, key, reader, contentType)
}

// UploadIfAbsent mocks base method.
func (m *MockBackend) UploadIfAbsent(ctx context.Context, key string, reader io.Reader, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadIfAbsent", ctx, key, reader, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadIfAbsent indicates an expected call of UploadIfAbsent.
func (mr *MockBackendMockRecorder) UploadIfAbsent(ctx, key, reader, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadIfAbsent", reflect.TypeOf((*MockBackend)(nil).UploadIfAbsent), ctx, key, reader, contentType)
}

// UploadWithOptions mocks base method.
func (m *MockBackend) UploadWithOptions(ctx context.Context, key string, reader io.Reader, contentType string, opts ...ports.UploadOption) (string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, reader, contentType}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UploadWithOptions", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadWithOptions indicates an expected call of UploadWithOptions.
func (mr *MockBackendMockRecorder) UploadWithOptions(ctx, key, reader, contentType any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, reader, contentType}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadWithOptions", reflect.TypeOf((*MockBackend)(nil).UploadWithOptions), varargs...)
}
