// Package constant defines stable Matcher product error codes.
package constant

// Matcher product error codes grouped by bounded context.
const (
	CodeInvalidRequest           = "MTCH-0001"
	CodeInternalServerError      = "MTCH-0002"
	CodeUnauthorized             = "MTCH-0003"
	CodeForbidden                = "MTCH-0004"
	CodeNotFound                 = "MTCH-0005"
	CodeUnprocessableEntity      = "MTCH-0006"
	CodeConflict                 = "MTCH-0007"
	CodeServiceUnavailable       = "MTCH-0008"
	CodeRateLimitExceeded        = "MTCH-0009"
	CodeRequestEntityTooLarge    = "MTCH-0010"
	CodeRequestFailed            = "MTCH-0011"
	CodeContextNotActive         = "MTCH-0012"
	CodeInvalidContextID         = "MTCH-0013"
	CodeInvalidIdempotencyKey    = "MTCH-0015"
	CodeIdempotencyConfiguration = "MTCH-0016"
	CodeIdempotencyError         = "MTCH-0017"
	CodeRequestInProgress        = "MTCH-0018"
	CodeObjectStorageUnavailable = "MTCH-0019"

	CodeConfigurationDuplicateName       = "MTCH-0101"
	CodeConfigurationPriorityConflict    = "MTCH-0102"
	CodeConfigurationInvalidState        = "MTCH-0103"
	CodeConfigurationArchivedContext     = "MTCH-0104"
	CodeConfigurationHasFieldMap         = "MTCH-0105"
	CodeConfigurationHasChildren         = "MTCH-0106"
	CodeConfigurationDuplicatePriority   = "MTCH-0107"
	CodeConfigurationFeeScheduleInUse    = "MTCH-0108"
	CodeConfigurationContextNameRequired = "MTCH-0109"
	CodeConfigurationContextNotFound     = "MTCH-0110"
	CodeConfigurationSourceNotFound      = "MTCH-0111"
	CodeConfigurationFieldMapNotFound    = "MTCH-0112"
	CodeConfigurationMatchRuleNotFound   = "MTCH-0113"
	CodeConfigurationFeeRuleNotFound     = "MTCH-0114"
	CodeConfigurationFeeScheduleNotFound = "MTCH-0115"
	CodeConfigurationScheduleNotFound    = "MTCH-0116"

	CodeDiscoveryConnectionNotFound = "MTCH-0201"
	CodeDiscoveryExtractionNotFound = "MTCH-0202"
	CodeDiscoveryFetcherUnavailable = "MTCH-0203"
	CodeDiscoveryInvalidExtraction  = "MTCH-0204"
	CodeDiscoveryRefreshInProgress  = "MTCH-0205"

	CodeIngestionSourceNotFound          = "MTCH-0301"
	CodeIngestionFieldMapNotFound        = "MTCH-0302"
	CodeIngestionFormatRequired          = "MTCH-0303"
	CodeIngestionEmptyFile               = "MTCH-0304"
	CodeIngestionInvalidState            = "MTCH-0305"
	CodeIngestionJobNotFound             = "MTCH-0306"
	CodeMatchingNoSourcesConfigured      = "MTCH-0401"
	CodeMatchingAtLeastTwoSources        = "MTCH-0402"
	CodeMatchingSourceSideRequired       = "MTCH-0403"
	CodeMatchingInvalidOneToOneTopology  = "MTCH-0404"
	CodeMatchingInvalidOneToManyTopology = "MTCH-0405"
	CodeMatchingFeeRulesMissing          = "MTCH-0406"
	CodeMatchingFeeRulesMisconfigured    = "MTCH-0407"
	CodeMatchingRunInProgress            = "MTCH-0408"

	CodeExceptionNotFound              = "MTCH-0501"
	CodeDisputeNotFound                = "MTCH-0502"
	CodeExceptionInvalidState          = "MTCH-0503"
	CodeCallbackInProgress             = "MTCH-0504"
	CodeCallbackRetryable              = "MTCH-0505"
	CodeCallbackRateLimitExceeded      = "MTCH-0506"
	CodeCommentNotFound                = "MTCH-0507"
	CodeDispatchTargetUnsupported      = "MTCH-0508"
	CodeDispatchConnectorNotConfigured = "MTCH-0509"

	CodeGovernanceAuditLogNotFound     = "MTCH-0601"
	CodeGovernanceActorMappingNotFound = "MTCH-0602"
	CodeGovernanceArchiveNotFound      = "MTCH-0603"

	CodeReportingExportJobNotFound    = "MTCH-0701"
	CodeReportingExportWorkerDisabled = "MTCH-0702"
	CodeReportingExportNotReady       = "MTCH-0703"
	CodeReportingExportExpired        = "MTCH-0704"
	CodeReportingInvalidExportFormat  = "MTCH-0705"
)
