package services

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"

	"github.com/LerianStudio/matcher/internal/shared/domain/fee"
)

// CandidateTransaction is the minimal stable view of a transaction used by evaluators.
// Avoid Metadata maps here to prevent nondeterministic iteration.
type CandidateTransaction struct {
	ID             uuid.UUID
	SourceID       uuid.UUID
	Amount         decimal.Decimal
	OriginalAmount decimal.Decimal // pre-normalization amount (always set)
	AmountBase     *decimal.Decimal
	FeeBreakdown   *fee.FeeBreakdown // nil if no schedule applies
	Currency       string
	CurrencyBase   string
	Reference      string
	Date           time.Time
}

// Allocation represents a partial amount assigned to a transaction.
type Allocation struct {
	TransactionID   uuid.UUID
	AllocatedAmount decimal.Decimal
	Currency        string
	UseBaseAmount   bool
}

// MatchProposal represents a proposed match between left and right transactions
// generated by a rule evaluation. RuleID identifies the rule, LeftIDs/RightIDs
// hold the matched transaction IDs, Score represents match quality (higher is better),
// and Mode describes the match shape (e.g., "1:1", "1:N", "N:1").
type MatchProposal struct {
	RuleID           uuid.UUID
	LeftIDs          []uuid.UUID
	RightIDs         []uuid.UUID
	LeftAllocations  []Allocation
	RightAllocations []Allocation
	Score            int
	Mode             string
}
