// Code generated by MockGen. DO NOT EDIT.
// Source: m2m.go
//
// Generated by this command:
//
//	mockgen -source=m2m.go -destination=mocks/m2m_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ports "github.com/LerianStudio/matcher/internal/shared/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockM2MProvider is a mock of M2MProvider interface.
type MockM2MProvider struct {
	ctrl     *gomock.Controller
	recorder *MockM2MProviderMockRecorder
	isgomock struct{}
}

// MockM2MProviderMockRecorder is the mock recorder for MockM2MProvider.
type MockM2MProviderMockRecorder struct {
	mock *MockM2MProvider
}

// NewMockM2MProvider creates a new mock instance.
func NewMockM2MProvider(ctrl *gomock.Controller) *MockM2MProvider {
	mock := &MockM2MProvider{ctrl: ctrl}
	mock.recorder = &MockM2MProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockM2MProvider) EXPECT() *MockM2MProviderMockRecorder {
	return m.recorder
}

// GetCredentials mocks base method.
func (m *MockM2MProvider) GetCredentials(ctx context.Context, tenantOrgID string) (*ports.M2MCredentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCredentials", ctx, tenantOrgID)
	ret0, _ := ret[0].(*ports.M2MCredentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCredentials indicates an expected call of GetCredentials.
func (mr *MockM2MProviderMockRecorder) GetCredentials(ctx, tenantOrgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCredentials", reflect.TypeOf((*MockM2MProvider)(nil).GetCredentials), ctx, tenantOrgID)
}

// InvalidateCredentials mocks base method.
func (m *MockM2MProvider) InvalidateCredentials(ctx context.Context, tenantOrgID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateCredentials", ctx, tenantOrgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateCredentials indicates an expected call of InvalidateCredentials.
func (mr *MockM2MProviderMockRecorder) InvalidateCredentials(ctx, tenantOrgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateCredentials", reflect.TypeOf((*MockM2MProvider)(nil).InvalidateCredentials), ctx, tenantOrgID)
}
