// Code generated by MockGen. DO NOT EDIT.
// Source: match_trigger.go
//
// Generated by this command:
//
//	mockgen -source=match_trigger.go -destination=mocks/match_trigger_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchTrigger is a mock of MatchTrigger interface.
type MockMatchTrigger struct {
	ctrl     *gomock.Controller
	recorder *MockMatchTriggerMockRecorder
	isgomock struct{}
}

// MockMatchTriggerMockRecorder is the mock recorder for MockMatchTrigger.
type MockMatchTriggerMockRecorder struct {
	mock *MockMatchTrigger
}

// NewMockMatchTrigger creates a new mock instance.
func NewMockMatchTrigger(ctrl *gomock.Controller) *MockMatchTrigger {
	mock := &MockMatchTrigger{ctrl: ctrl}
	mock.recorder = &MockMatchTriggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchTrigger) EXPECT() *MockMatchTriggerMockRecorder {
	return m.recorder
}

// TriggerMatchForContext mocks base method.
func (m *MockMatchTrigger) TriggerMatchForContext(ctx context.Context, tenantID, contextID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TriggerMatchForContext", ctx, tenantID, contextID)
}

// TriggerMatchForContext indicates an expected call of TriggerMatchForContext.
func (mr *MockMatchTriggerMockRecorder) TriggerMatchForContext(ctx, tenantID, contextID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerMatchForContext", reflect.TypeOf((*MockMatchTrigger)(nil).TriggerMatchForContext), ctx, tenantID, contextID)
}

// MockContextProvider is a mock of ContextProvider interface.
type MockContextProvider struct {
	ctrl     *gomock.Controller
	recorder *MockContextProviderMockRecorder
	isgomock struct{}
}

// MockContextProviderMockRecorder is the mock recorder for MockContextProvider.
type MockContextProviderMockRecorder struct {
	mock *MockContextProvider
}

// NewMockContextProvider creates a new mock instance.
func NewMockContextProvider(ctrl *gomock.Controller) *MockContextProvider {
	mock := &MockContextProvider{ctrl: ctrl}
	mock.recorder = &MockContextProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextProvider) EXPECT() *MockContextProviderMockRecorder {
	return m.recorder
}

// IsAutoMatchEnabled mocks base method.
func (m *MockContextProvider) IsAutoMatchEnabled(ctx context.Context, contextID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAutoMatchEnabled", ctx, contextID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAutoMatchEnabled indicates an expected call of IsAutoMatchEnabled.
func (mr *MockContextProviderMockRecorder) IsAutoMatchEnabled(ctx, contextID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAutoMatchEnabled", reflect.TypeOf((*MockContextProvider)(nil).IsAutoMatchEnabled), ctx, contextID)
}
