// Code generated by MockGen. DO NOT EDIT.
// Source: actor_mapping_repository.go
//
// Generated by this command:
//
//	mockgen -source=actor_mapping_repository.go -destination=mocks/actor_mapping_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/LerianStudio/matcher/internal/governance/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockActorMappingRepository is a mock of ActorMappingRepository interface.
type MockActorMappingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockActorMappingRepositoryMockRecorder
	isgomock struct{}
}

// MockActorMappingRepositoryMockRecorder is the mock recorder for MockActorMappingRepository.
type MockActorMappingRepositoryMockRecorder struct {
	mock *MockActorMappingRepository
}

// NewMockActorMappingRepository creates a new mock instance.
func NewMockActorMappingRepository(ctrl *gomock.Controller) *MockActorMappingRepository {
	mock := &MockActorMappingRepository{ctrl: ctrl}
	mock.recorder = &MockActorMappingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActorMappingRepository) EXPECT() *MockActorMappingRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockActorMappingRepository) Delete(ctx context.Context, actorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, actorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockActorMappingRepositoryMockRecorder) Delete(ctx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockActorMappingRepository)(nil).Delete), ctx, actorID)
}

// GetByActorID mocks base method.
func (m *MockActorMappingRepository) GetByActorID(ctx context.Context, actorID string) (*entities.ActorMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByActorID", ctx, actorID)
	ret0, _ := ret[0].(*entities.ActorMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByActorID indicates an expected call of GetByActorID.
func (mr *MockActorMappingRepositoryMockRecorder) GetByActorID(ctx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByActorID", reflect.TypeOf((*MockActorMappingRepository)(nil).GetByActorID), ctx, actorID)
}

// Pseudonymize mocks base method.
func (m *MockActorMappingRepository) Pseudonymize(ctx context.Context, actorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pseudonymize", ctx, actorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pseudonymize indicates an expected call of Pseudonymize.
func (mr *MockActorMappingRepositoryMockRecorder) Pseudonymize(ctx, actorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pseudonymize", reflect.TypeOf((*MockActorMappingRepository)(nil).Pseudonymize), ctx, actorID)
}

// Upsert mocks base method.
func (m *MockActorMappingRepository) Upsert(ctx context.Context, mapping *entities.ActorMapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, mapping)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockActorMappingRepositoryMockRecorder) Upsert(ctx, mapping any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockActorMappingRepository)(nil).Upsert), ctx, mapping)
}
