// Code generated by MockGen. DO NOT EDIT.
// Source: archive_metadata_repository.go
//
// Generated by this command:
//
//	mockgen -source=archive_metadata_repository.go -destination=mocks/archive_metadata_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	entities "github.com/LerianStudio/matcher/internal/governance/domain/entities"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockArchiveMetadataRepository is a mock of ArchiveMetadataRepository interface.
type MockArchiveMetadataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockArchiveMetadataRepositoryMockRecorder
	isgomock struct{}
}

// MockArchiveMetadataRepositoryMockRecorder is the mock recorder for MockArchiveMetadataRepository.
type MockArchiveMetadataRepositoryMockRecorder struct {
	mock *MockArchiveMetadataRepository
}

// NewMockArchiveMetadataRepository creates a new mock instance.
func NewMockArchiveMetadataRepository(ctrl *gomock.Controller) *MockArchiveMetadataRepository {
	mock := &MockArchiveMetadataRepository{ctrl: ctrl}
	mock.recorder = &MockArchiveMetadataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArchiveMetadataRepository) EXPECT() *MockArchiveMetadataRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockArchiveMetadataRepository) Create(ctx context.Context, metadata *entities.ArchiveMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockArchiveMetadataRepositoryMockRecorder) Create(ctx, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockArchiveMetadataRepository)(nil).Create), ctx, metadata)
}

// CreateWithTx mocks base method.
func (m *MockArchiveMetadataRepository) CreateWithTx(ctx context.Context, tx *sql.Tx, metadata *entities.ArchiveMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, tx, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockArchiveMetadataRepositoryMockRecorder) CreateWithTx(ctx, tx, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockArchiveMetadataRepository)(nil).CreateWithTx), ctx, tx, metadata)
}

// GetByID mocks base method.
func (m *MockArchiveMetadataRepository) GetByID(ctx context.Context, id uuid.UUID) (*entities.ArchiveMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.ArchiveMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockArchiveMetadataRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockArchiveMetadataRepository)(nil).GetByID), ctx, id)
}

// GetByPartition mocks base method.
func (m *MockArchiveMetadataRepository) GetByPartition(ctx context.Context, tenantID uuid.UUID, partitionName string) (*entities.ArchiveMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPartition", ctx, tenantID, partitionName)
	ret0, _ := ret[0].(*entities.ArchiveMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPartition indicates an expected call of GetByPartition.
func (mr *MockArchiveMetadataRepositoryMockRecorder) GetByPartition(ctx, tenantID, partitionName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPartition", reflect.TypeOf((*MockArchiveMetadataRepository)(nil).GetByPartition), ctx, tenantID, partitionName)
}

// ListByTenant mocks base method.
func (m *MockArchiveMetadataRepository) ListByTenant(ctx context.Context, tenantID uuid.UUID, status entities.ArchiveStatus, from, to *time.Time, limit, offset int) ([]*entities.ArchiveMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenant", ctx, tenantID, status, from, to, limit, offset)
	ret0, _ := ret[0].([]*entities.ArchiveMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenant indicates an expected call of ListByTenant.
func (mr *MockArchiveMetadataRepositoryMockRecorder) ListByTenant(ctx, tenantID, status, from, to, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenant", reflect.TypeOf((*MockArchiveMetadataRepository)(nil).ListByTenant), ctx, tenantID, status, from, to, limit, offset)
}

// ListIncomplete mocks base method.
func (m *MockArchiveMetadataRepository) ListIncomplete(ctx context.Context) ([]*entities.ArchiveMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncomplete", ctx)
	ret0, _ := ret[0].([]*entities.ArchiveMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncomplete indicates an expected call of ListIncomplete.
func (mr *MockArchiveMetadataRepositoryMockRecorder) ListIncomplete(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncomplete", reflect.TypeOf((*MockArchiveMetadataRepository)(nil).ListIncomplete), ctx)
}

// ListPending mocks base method.
func (m *MockArchiveMetadataRepository) ListPending(ctx context.Context) ([]*entities.ArchiveMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx)
	ret0, _ := ret[0].([]*entities.ArchiveMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockArchiveMetadataRepositoryMockRecorder) ListPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockArchiveMetadataRepository)(nil).ListPending), ctx)
}

// Update mocks base method.
func (m *MockArchiveMetadataRepository) Update(ctx context.Context, metadata *entities.ArchiveMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockArchiveMetadataRepositoryMockRecorder) Update(ctx, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockArchiveMetadataRepository)(nil).Update), ctx, metadata)
}

// UpdateWithTx mocks base method.
func (m *MockArchiveMetadataRepository) UpdateWithTx(ctx context.Context, tx *sql.Tx, metadata *entities.ArchiveMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithTx", ctx, tx, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithTx indicates an expected call of UpdateWithTx.
func (mr *MockArchiveMetadataRepositoryMockRecorder) UpdateWithTx(ctx, tx, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithTx", reflect.TypeOf((*MockArchiveMetadataRepository)(nil).UpdateWithTx), ctx, tx, metadata)
}
