// Code generated by MockGen. DO NOT EDIT.
// Source: audit_repository.go
//
// Generated by this command:
//
//	mockgen -source=audit_repository.go -destination=mocks/audit_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
