// Code generated by MockGen. DO NOT EDIT.
// Source: internal/shared/ports/audit.go
//
// Generated by this command:
//
//	mockgen -source=internal/shared/ports/audit.go -destination=internal/governance/domain/repositories/mocks/audit_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	http "github.com/LerianStudio/lib-commons/v4/commons/net/http"
	shared "github.com/LerianStudio/matcher/internal/shared/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditLogRepository is a mock of AuditLogRepository interface.
type MockAuditLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditLogRepositoryMockRecorder is the mock recorder for MockAuditLogRepository.
type MockAuditLogRepositoryMockRecorder struct {
	mock *MockAuditLogRepository
}

// NewMockAuditLogRepository creates a new mock instance.
func NewMockAuditLogRepository(ctrl *gomock.Controller) *MockAuditLogRepository {
	mock := &MockAuditLogRepository{ctrl: ctrl}
	mock.recorder = &MockAuditLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogRepository) EXPECT() *MockAuditLogRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuditLogRepository) Create(ctx context.Context, auditLog *shared.AuditLog) (*shared.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, auditLog)
	ret0, _ := ret[0].(*shared.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAuditLogRepositoryMockRecorder) Create(ctx, auditLog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuditLogRepository)(nil).Create), ctx, auditLog)
}

// CreateWithTx mocks base method.
func (m *MockAuditLogRepository) CreateWithTx(ctx context.Context, tx *sql.Tx, auditLog *shared.AuditLog) (*shared.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, tx, auditLog)
	ret0, _ := ret[0].(*shared.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockAuditLogRepositoryMockRecorder) CreateWithTx(ctx, tx, auditLog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockAuditLogRepository)(nil).CreateWithTx), ctx, tx, auditLog)
}

// GetByID mocks base method.
func (m *MockAuditLogRepository) GetByID(ctx context.Context, id uuid.UUID) (*shared.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*shared.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAuditLogRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAuditLogRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockAuditLogRepository) List(ctx context.Context, filter shared.AuditLogFilter, cursor *http.TimestampCursor, limit int) ([]*shared.AuditLog, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, cursor, limit)
	ret0, _ := ret[0].([]*shared.AuditLog)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAuditLogRepositoryMockRecorder) List(ctx, filter, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAuditLogRepository)(nil).List), ctx, filter, cursor, limit)
}

// ListByEntity mocks base method.
func (m *MockAuditLogRepository) ListByEntity(ctx context.Context, entityType string, entityID uuid.UUID, cursor *http.TimestampCursor, limit int) ([]*shared.AuditLog, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByEntity", ctx, entityType, entityID, cursor, limit)
	ret0, _ := ret[0].([]*shared.AuditLog)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByEntity indicates an expected call of ListByEntity.
func (mr *MockAuditLogRepositoryMockRecorder) ListByEntity(ctx, entityType, entityID, cursor, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByEntity", reflect.TypeOf((*MockAuditLogRepository)(nil).ListByEntity), ctx, entityType, entityID, cursor, limit)
}
