// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/matching/ports (interfaces: ContextProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/context_provider_mock.go -package=mocks . ContextProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ports "github.com/LerianStudio/matcher/internal/matching/ports"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockContextProvider is a mock of ContextProvider interface.
type MockContextProvider struct {
	ctrl     *gomock.Controller
	recorder *MockContextProviderMockRecorder
	isgomock struct{}
}

// MockContextProviderMockRecorder is the mock recorder for MockContextProvider.
type MockContextProviderMockRecorder struct {
	mock *MockContextProvider
}

// NewMockContextProvider creates a new mock instance.
func NewMockContextProvider(ctrl *gomock.Controller) *MockContextProvider {
	mock := &MockContextProvider{ctrl: ctrl}
	mock.recorder = &MockContextProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextProvider) EXPECT() *MockContextProviderMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockContextProvider) FindByID(ctx context.Context, tenantID, contextID uuid.UUID) (*ports.ReconciliationContextInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, tenantID, contextID)
	ret0, _ := ret[0].(*ports.ReconciliationContextInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockContextProviderMockRecorder) FindByID(ctx, tenantID, contextID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockContextProvider)(nil).FindByID), ctx, tenantID, contextID)
}
