// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/matching/ports (interfaces: MatchEventPublisher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/event_publisher_mock.go -package=mocks . MatchEventPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	shared "github.com/LerianStudio/matcher/internal/shared/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchEventPublisher is a mock of MatchEventPublisher interface.
type MockMatchEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockMatchEventPublisherMockRecorder
	isgomock struct{}
}

// MockMatchEventPublisherMockRecorder is the mock recorder for MockMatchEventPublisher.
type MockMatchEventPublisherMockRecorder struct {
	mock *MockMatchEventPublisher
}

// NewMockMatchEventPublisher creates a new mock instance.
func NewMockMatchEventPublisher(ctrl *gomock.Controller) *MockMatchEventPublisher {
	mock := &MockMatchEventPublisher{ctrl: ctrl}
	mock.recorder = &MockMatchEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchEventPublisher) EXPECT() *MockMatchEventPublisherMockRecorder {
	return m.recorder
}

// PublishMatchConfirmed mocks base method.
func (m *MockMatchEventPublisher) PublishMatchConfirmed(ctx context.Context, event *shared.MatchConfirmedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMatchConfirmed", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishMatchConfirmed indicates an expected call of PublishMatchConfirmed.
func (mr *MockMatchEventPublisherMockRecorder) PublishMatchConfirmed(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMatchConfirmed", reflect.TypeOf((*MockMatchEventPublisher)(nil).PublishMatchConfirmed), ctx, event)
}

// PublishMatchUnmatched mocks base method.
func (m *MockMatchEventPublisher) PublishMatchUnmatched(ctx context.Context, event *shared.MatchUnmatchedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMatchUnmatched", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishMatchUnmatched indicates an expected call of PublishMatchUnmatched.
func (mr *MockMatchEventPublisherMockRecorder) PublishMatchUnmatched(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMatchUnmatched", reflect.TypeOf((*MockMatchEventPublisher)(nil).PublishMatchUnmatched), ctx, event)
}
