// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/matching/ports (interfaces: ExceptionCreator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/exception_creator_mock.go -package=mocks . ExceptionCreator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repositories "github.com/LerianStudio/matcher/internal/matching/domain/repositories"
	ports "github.com/LerianStudio/matcher/internal/matching/ports"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockExceptionCreator is a mock of ExceptionCreator interface.
type MockExceptionCreator struct {
	ctrl     *gomock.Controller
	recorder *MockExceptionCreatorMockRecorder
	isgomock struct{}
}

// MockExceptionCreatorMockRecorder is the mock recorder for MockExceptionCreator.
type MockExceptionCreatorMockRecorder struct {
	mock *MockExceptionCreator
}

// NewMockExceptionCreator creates a new mock instance.
func NewMockExceptionCreator(ctrl *gomock.Controller) *MockExceptionCreator {
	mock := &MockExceptionCreator{ctrl: ctrl}
	mock.recorder = &MockExceptionCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExceptionCreator) EXPECT() *MockExceptionCreatorMockRecorder {
	return m.recorder
}

// CreateExceptions mocks base method.
func (m *MockExceptionCreator) CreateExceptions(ctx context.Context, contextID, runID uuid.UUID, inputs []ports.ExceptionTransactionInput, regulatorySourceTypes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExceptions", ctx, contextID, runID, inputs, regulatorySourceTypes)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateExceptions indicates an expected call of CreateExceptions.
func (mr *MockExceptionCreatorMockRecorder) CreateExceptions(ctx, contextID, runID, inputs, regulatorySourceTypes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExceptions", reflect.TypeOf((*MockExceptionCreator)(nil).CreateExceptions), ctx, contextID, runID, inputs, regulatorySourceTypes)
}

// CreateExceptionsWithTx mocks base method.
func (m *MockExceptionCreator) CreateExceptionsWithTx(ctx context.Context, tx repositories.Tx, contextID, runID uuid.UUID, inputs []ports.ExceptionTransactionInput, regulatorySourceTypes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExceptionsWithTx", ctx, tx, contextID, runID, inputs, regulatorySourceTypes)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateExceptionsWithTx indicates an expected call of CreateExceptionsWithTx.
func (mr *MockExceptionCreatorMockRecorder) CreateExceptionsWithTx(ctx, tx, contextID, runID, inputs, regulatorySourceTypes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExceptionsWithTx", reflect.TypeOf((*MockExceptionCreator)(nil).CreateExceptionsWithTx), ctx, tx, contextID, runID, inputs, regulatorySourceTypes)
}
