// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/matching/ports (interfaces: MatchRuleProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/match_rule_provider_mock.go -package=mocks . MatchRuleProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	shared "github.com/LerianStudio/matcher/internal/shared/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchRuleProvider is a mock of MatchRuleProvider interface.
type MockMatchRuleProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMatchRuleProviderMockRecorder
	isgomock struct{}
}

// MockMatchRuleProviderMockRecorder is the mock recorder for MockMatchRuleProvider.
type MockMatchRuleProviderMockRecorder struct {
	mock *MockMatchRuleProvider
}

// NewMockMatchRuleProvider creates a new mock instance.
func NewMockMatchRuleProvider(ctrl *gomock.Controller) *MockMatchRuleProvider {
	mock := &MockMatchRuleProvider{ctrl: ctrl}
	mock.recorder = &MockMatchRuleProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchRuleProvider) EXPECT() *MockMatchRuleProviderMockRecorder {
	return m.recorder
}

// ListByContextID mocks base method.
func (m *MockMatchRuleProvider) ListByContextID(ctx context.Context, contextID uuid.UUID) (shared.MatchRules, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByContextID", ctx, contextID)
	ret0, _ := ret[0].(shared.MatchRules)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByContextID indicates an expected call of ListByContextID.
func (mr *MockMatchRuleProviderMockRecorder) ListByContextID(ctx, contextID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByContextID", reflect.TypeOf((*MockMatchRuleProvider)(nil).ListByContextID), ctx, contextID)
}
