// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/matching/ports (interfaces: SourceProvider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/source_provider_mock.go -package=mocks . SourceProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ports "github.com/LerianStudio/matcher/internal/matching/ports"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSourceProvider is a mock of SourceProvider interface.
type MockSourceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSourceProviderMockRecorder
	isgomock struct{}
}

// MockSourceProviderMockRecorder is the mock recorder for MockSourceProvider.
type MockSourceProviderMockRecorder struct {
	mock *MockSourceProvider
}

// NewMockSourceProvider creates a new mock instance.
func NewMockSourceProvider(ctrl *gomock.Controller) *MockSourceProvider {
	mock := &MockSourceProvider{ctrl: ctrl}
	mock.recorder = &MockSourceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceProvider) EXPECT() *MockSourceProviderMockRecorder {
	return m.recorder
}

// FindByContextID mocks base method.
func (m *MockSourceProvider) FindByContextID(ctx context.Context, contextID uuid.UUID) ([]*ports.SourceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByContextID", ctx, contextID)
	ret0, _ := ret[0].([]*ports.SourceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByContextID indicates an expected call of FindByContextID.
func (mr *MockSourceProviderMockRecorder) FindByContextID(ctx, contextID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByContextID", reflect.TypeOf((*MockSourceProvider)(nil).FindByContextID), ctx, contextID)
}
