// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/matching/ports (interfaces: TransactionRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/transaction_repository_mock.go -package=mocks . TransactionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	repositories "github.com/LerianStudio/matcher/internal/matching/domain/repositories"
	shared "github.com/LerianStudio/matcher/internal/shared/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// FindByContextAndIDs mocks base method.
func (m *MockTransactionRepository) FindByContextAndIDs(ctx context.Context, contextID uuid.UUID, transactionIDs []uuid.UUID) ([]*shared.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByContextAndIDs", ctx, contextID, transactionIDs)
	ret0, _ := ret[0].([]*shared.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByContextAndIDs indicates an expected call of FindByContextAndIDs.
func (mr *MockTransactionRepositoryMockRecorder) FindByContextAndIDs(ctx, contextID, transactionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByContextAndIDs", reflect.TypeOf((*MockTransactionRepository)(nil).FindByContextAndIDs), ctx, contextID, transactionIDs)
}

// ListUnmatchedByContext mocks base method.
func (m *MockTransactionRepository) ListUnmatchedByContext(ctx context.Context, contextID uuid.UUID, startInclusive, endInclusive *time.Time, limit, offset int) ([]*shared.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnmatchedByContext", ctx, contextID, startInclusive, endInclusive, limit, offset)
	ret0, _ := ret[0].([]*shared.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnmatchedByContext indicates an expected call of ListUnmatchedByContext.
func (mr *MockTransactionRepositoryMockRecorder) ListUnmatchedByContext(ctx, contextID, startInclusive, endInclusive, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnmatchedByContext", reflect.TypeOf((*MockTransactionRepository)(nil).ListUnmatchedByContext), ctx, contextID, startInclusive, endInclusive, limit, offset)
}

// MarkMatchedWithTx mocks base method.
func (m *MockTransactionRepository) MarkMatchedWithTx(ctx context.Context, tx repositories.Tx, contextID uuid.UUID, transactionIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMatchedWithTx", ctx, tx, contextID, transactionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkMatchedWithTx indicates an expected call of MarkMatchedWithTx.
func (mr *MockTransactionRepositoryMockRecorder) MarkMatchedWithTx(ctx, tx, contextID, transactionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMatchedWithTx", reflect.TypeOf((*MockTransactionRepository)(nil).MarkMatchedWithTx), ctx, tx, contextID, transactionIDs)
}

// MarkPendingReviewWithTx mocks base method.
func (m *MockTransactionRepository) MarkPendingReviewWithTx(ctx context.Context, tx repositories.Tx, contextID uuid.UUID, transactionIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPendingReviewWithTx", ctx, tx, contextID, transactionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPendingReviewWithTx indicates an expected call of MarkPendingReviewWithTx.
func (mr *MockTransactionRepositoryMockRecorder) MarkPendingReviewWithTx(ctx, tx, contextID, transactionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPendingReviewWithTx", reflect.TypeOf((*MockTransactionRepository)(nil).MarkPendingReviewWithTx), ctx, tx, contextID, transactionIDs)
}

// MarkUnmatchedWithTx mocks base method.
func (m *MockTransactionRepository) MarkUnmatchedWithTx(ctx context.Context, tx repositories.Tx, contextID uuid.UUID, transactionIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUnmatchedWithTx", ctx, tx, contextID, transactionIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUnmatchedWithTx indicates an expected call of MarkUnmatchedWithTx.
func (mr *MockTransactionRepositoryMockRecorder) MarkUnmatchedWithTx(ctx, tx, contextID, transactionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUnmatchedWithTx", reflect.TypeOf((*MockTransactionRepository)(nil).MarkUnmatchedWithTx), ctx, tx, contextID, transactionIDs)
}

// WithTx mocks base method.
func (m *MockTransactionRepository) WithTx(ctx context.Context, fn func(repositories.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTransactionRepositoryMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTransactionRepository)(nil).WithTx), ctx, fn)
}
