// Copyright 2026 Lerian Studio. All rights reserved.
// Use of this source code is governed by an Elastic License 2.0
// that can be found in the LICENSE.md file.

// Package catalog defines Matcher's canonical lib-streaming event catalog.
package catalog

import (
	"fmt"

	streaming "github.com/LerianStudio/lib-streaming/v2"
)

// EventCount is the canonical number of streaming event definitions in Matcher.
const EventCount = 46

var definitions = [...]streaming.EventDefinition{
	{
		Key:             "reconciliation_context.created",
		ResourceType:    "reconciliation_context",
		EventType:       "created",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A reconciliation context was durably created for a tenant, establishing matching topology and configuration defaults.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "reconciliation_context.updated",
		ResourceType:    "reconciliation_context",
		EventType:       "updated",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A reconciliation context was durably updated, changing tenant-scoped matching metadata or lifecycle status.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "reconciliation_context.deleted",
		ResourceType:    "reconciliation_context",
		EventType:       "deleted",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A reconciliation context was durably deleted after child-entity safeguards passed for the tenant.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "reconciliation_source.created",
		ResourceType:    "reconciliation_source",
		EventType:       "created",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A reconciliation source was durably created within a tenant context, defining an input side for matching.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "match_rule.created",
		ResourceType:    "match_rule",
		EventType:       "created",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A match rule was durably created for a reconciliation context, adding tenant-scoped matching behavior.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "match_rule.reordered",
		ResourceType:    "match_rule",
		EventType:       "reordered",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "Match rule priorities were durably reordered for a reconciliation context, changing evaluation order.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "fetcher_connection.synced",
		ResourceType:    "fetcher_connection",
		EventType:       "synced",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A tenant-scoped Fetcher connection and its discovered schema snapshot were synchronized into Matcher persistence.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "fetcher_connection.unreachable",
		ResourceType:    "fetcher_connection",
		EventType:       "unreachable",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A tenant-scoped Fetcher connection was marked unreachable and its stale discovered schema state was cleared.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "extraction_request.created",
		ResourceType:    "extraction_request",
		EventType:       "created",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A tenant-scoped extraction request was created in Matcher before submission to the external Fetcher service.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "extraction_request.submitted",
		ResourceType:    "extraction_request",
		EventType:       "submitted",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A tenant-scoped extraction request was durably marked submitted after Fetcher accepted the extraction job.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "extraction_request.completed",
		ResourceType:    "extraction_request",
		EventType:       "completed",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A tenant-scoped extraction request reached the durable COMPLETE terminal state with a Fetcher result artifact path.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "extraction_request.failed",
		ResourceType:    "extraction_request",
		EventType:       "failed",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A tenant-scoped extraction request reached the durable FAILED terminal state after Fetcher reported failure.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "extraction_request.cancelled",
		ResourceType:    "extraction_request",
		EventType:       "cancelled",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A tenant-scoped extraction request reached the durable CANCELLED terminal state after remote cancellation or disappearance.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "extraction_request.bridged",
		ResourceType:    "extraction_request",
		EventType:       "bridged",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A tenant-scoped completed extraction was durably linked to the ingestion job created from its verified artifact.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "extraction_request.bridge_failed",
		ResourceType:    "extraction_request",
		EventType:       "bridge_failed",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A tenant-scoped completed extraction was durably marked with a terminal bridge failure after retry classification.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "ingestion.completed",
		ResourceType:    "ingestion",
		EventType:       "completed",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "An ingestion job finished successfully and its imported transaction counts were durably recorded.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "ingestion.failed",
		ResourceType:    "ingestion",
		EventType:       "failed",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "An ingestion job reached the failed terminal state and its failure metadata was durably recorded.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "transaction.ignored",
		ResourceType:    "transaction",
		EventType:       "ignored",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A previously unmatched transaction was durably marked as ignored and excluded from automatic matching.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "match_run.completed",
		ResourceType:    "match_run",
		EventType:       "completed",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A matching run completed successfully and its terminal statistics were durably persisted for a reconciliation context.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "match_run.failed",
		ResourceType:    "match_run",
		EventType:       "failed",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A matching run reached the failed terminal state and its failure reason was durably persisted for the tenant.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "match_group.confirmed",
		ResourceType:    "match_group",
		EventType:       "confirmed",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A match group was durably confirmed, binding its transactions to a reconciliation match within a completed run.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "match_group.unmatched",
		ResourceType:    "match_group",
		EventType:       "unmatched",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A previously confirmed match group was durably revoked and its transactions were reverted to unmatched status.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "transaction.matched",
		ResourceType:    "transaction",
		EventType:       "matched",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A transaction was durably marked as matched as part of committing reconciliation match results for a tenant context.",
		// Outbox-only delivery: high-cardinality per-transaction event in the
		// match-run commit path. Direct broker emission would create N+1
		// synchronous round-trips on the hot path; outbox provides eventual
		// consistency with batched delivery via the outbox dispatcher.
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "transaction.pending_review",
		ResourceType:    "transaction",
		EventType:       "pending_review",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A transaction was durably marked as pending review because reconciliation found a non-automatic match candidate.",
		// Outbox-only delivery: high-cardinality per-transaction event in the
		// match-run commit path. Direct broker emission would create N+1
		// synchronous round-trips on the hot path; outbox provides eventual
		// consistency with batched delivery via the outbox dispatcher.
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "fee_variance.created",
		ResourceType:    "fee_variance",
		EventType:       "created",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A fee variance was durably recorded after matching detected a difference between expected and actual fees.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "exception.assigned",
		ResourceType:    "exception",
		EventType:       "assigned",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "An exception was durably assigned to an owner for follow-up and SLA accountability.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "exception.resolved",
		ResourceType:    "exception",
		EventType:       "resolved",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "An exception was durably resolved through the bulk resolution path with resolution details persisted.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "exception.dispatched",
		ResourceType:    "exception",
		EventType:       "dispatched",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "An exception was sent to an external target and the dispatch audit trail was durably persisted.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "exception.callback_processed",
		ResourceType:    "exception",
		EventType:       "callback_processed",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "An external callback was processed and its exception state or metadata changes were durably persisted.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "exception_comment.added",
		ResourceType:    "exception_comment",
		EventType:       "added",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A comment was durably added to an exception for case collaboration and review history.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "exception_comment.deleted",
		ResourceType:    "exception_comment",
		EventType:       "deleted",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A previously persisted exception comment was durably deleted by its author within tenant scope.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "dispute.opened",
		ResourceType:    "dispute",
		EventType:       "opened",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A dispute was durably opened for an exception and entered the active dispute lifecycle.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "dispute.won",
		ResourceType:    "dispute",
		EventType:       "won",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A dispute was durably closed as won with resolution details persisted for the exception.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "dispute.lost",
		ResourceType:    "dispute",
		EventType:       "lost",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A dispute was durably closed as lost with resolution details persisted for the exception.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "evidence.submitted",
		ResourceType:    "evidence",
		EventType:       "submitted",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "Evidence was durably submitted to a dispute and appended to the persisted dispute record.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "exception.force_match_resolved",
		ResourceType:    "exception",
		EventType:       "force_match_resolved",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "An exception was durably resolved by force matching the related transaction with an override reason.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "exception.adjust_entry_resolved",
		ResourceType:    "exception",
		EventType:       "adjust_entry_resolved",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "An exception was durably resolved by applying an adjustment entry to the related financial record.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "audit_log.created",
		ResourceType:    "audit_log",
		EventType:       "created",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "An immutable tenant-scoped audit log entry was appended to the compliance hash chain after durable persistence.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "archive_metadata.created",
		ResourceType:    "archive_metadata",
		EventType:       "created",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A tenant audit-log partition archive metadata record was durably created to start the compliance archival lifecycle.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "archive.uploaded",
		ResourceType:    "archive",
		EventType:       "uploaded",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A tenant audit-log archive object was uploaded and its archive metadata was durably advanced to the uploaded state.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "archive.completed",
		ResourceType:    "archive",
		EventType:       "completed",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A tenant audit-log partition archive was verified, detached, dropped, and durably marked complete in governance metadata.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "actor.pseudonymized",
		ResourceType:    "actor",
		EventType:       "pseudonymized",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A tenant actor mapping had its personally identifying fields durably replaced with redacted values for compliance.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("skip"),
			Outbox:  streaming.OutboxMode("always"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "export_job.created",
		ResourceType:    "export_job",
		EventType:       "created",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "An asynchronous reporting export job was durably created and queued for tenant-scoped processing.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "export_job.succeeded",
		ResourceType:    "export_job",
		EventType:       "succeeded",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A reporting export job completed successfully and its generated file metadata was durably persisted.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "export_job.failed",
		ResourceType:    "export_job",
		EventType:       "failed",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A reporting export job reached a terminal failed state after retry handling and the failure status was persisted.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
	{
		Key:             "export_job.expired",
		ResourceType:    "export_job",
		EventType:       "expired",
		SchemaVersion:   "1.0.0",
		DataContentType: "application/json",
		DataSchema:      "",
		SystemEvent:     false,
		Description:     "A reporting export job was marked expired, preventing new downloads of the tenant-scoped export artifact.",
		DefaultPolicy: streaming.DeliveryPolicy{
			Enabled: true,
			Direct:  streaming.DirectMode("direct"),
			Outbox:  streaming.OutboxMode("fallback_on_circuit_open"),
			DLQ:     streaming.DLQMode("on_routable_failure"),
		},
	},
}

// Definitions returns a defensive copy of Matcher's canonical streaming event definitions.
func Definitions() []streaming.EventDefinition {
	out := make([]streaming.EventDefinition, len(definitions))
	copy(out, definitions[:])

	return out
}

// NewCatalog builds Matcher's canonical lib-streaming catalog.
func NewCatalog() (streaming.Catalog, error) {
	defs := Definitions()

	catalog, err := streaming.NewCatalog(defs...)
	if err != nil {
		return streaming.Catalog{}, fmt.Errorf("build matcher streaming catalog: %w", err)
	}

	return catalog, nil
}
