// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -source=cache.go -destination=mocks/dashboard_cache_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/LerianStudio/matcher/internal/reporting/domain/entities"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockDashboardCacheService is a mock of DashboardCacheService interface.
type MockDashboardCacheService struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardCacheServiceMockRecorder
	isgomock struct{}
}

// MockDashboardCacheServiceMockRecorder is the mock recorder for MockDashboardCacheService.
type MockDashboardCacheServiceMockRecorder struct {
	mock *MockDashboardCacheService
}

// NewMockDashboardCacheService creates a new mock instance.
func NewMockDashboardCacheService(ctrl *gomock.Controller) *MockDashboardCacheService {
	mock := &MockDashboardCacheService{ctrl: ctrl}
	mock.recorder = &MockDashboardCacheServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboardCacheService) EXPECT() *MockDashboardCacheServiceMockRecorder {
	return m.recorder
}

// GetDashboardAggregates mocks base method.
func (m *MockDashboardCacheService) GetDashboardAggregates(ctx context.Context, filter entities.DashboardFilter) (*entities.DashboardAggregates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardAggregates", ctx, filter)
	ret0, _ := ret[0].(*entities.DashboardAggregates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardAggregates indicates an expected call of GetDashboardAggregates.
func (mr *MockDashboardCacheServiceMockRecorder) GetDashboardAggregates(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardAggregates", reflect.TypeOf((*MockDashboardCacheService)(nil).GetDashboardAggregates), ctx, filter)
}

// GetMatchRateStats mocks base method.
func (m *MockDashboardCacheService) GetMatchRateStats(ctx context.Context, filter entities.DashboardFilter) (*entities.MatchRateStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchRateStats", ctx, filter)
	ret0, _ := ret[0].(*entities.MatchRateStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatchRateStats indicates an expected call of GetMatchRateStats.
func (mr *MockDashboardCacheServiceMockRecorder) GetMatchRateStats(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchRateStats", reflect.TypeOf((*MockDashboardCacheService)(nil).GetMatchRateStats), ctx, filter)
}

// GetMatcherDashboardMetrics mocks base method.
func (m *MockDashboardCacheService) GetMatcherDashboardMetrics(ctx context.Context, filter entities.DashboardFilter) (*entities.MatcherDashboardMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatcherDashboardMetrics", ctx, filter)
	ret0, _ := ret[0].(*entities.MatcherDashboardMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatcherDashboardMetrics indicates an expected call of GetMatcherDashboardMetrics.
func (mr *MockDashboardCacheServiceMockRecorder) GetMatcherDashboardMetrics(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatcherDashboardMetrics", reflect.TypeOf((*MockDashboardCacheService)(nil).GetMatcherDashboardMetrics), ctx, filter)
}

// GetSLAStats mocks base method.
func (m *MockDashboardCacheService) GetSLAStats(ctx context.Context, filter entities.DashboardFilter) (*entities.SLAStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSLAStats", ctx, filter)
	ret0, _ := ret[0].(*entities.SLAStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSLAStats indicates an expected call of GetSLAStats.
func (mr *MockDashboardCacheServiceMockRecorder) GetSLAStats(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSLAStats", reflect.TypeOf((*MockDashboardCacheService)(nil).GetSLAStats), ctx, filter)
}

// GetVolumeStats mocks base method.
func (m *MockDashboardCacheService) GetVolumeStats(ctx context.Context, filter entities.DashboardFilter) (*entities.VolumeStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolumeStats", ctx, filter)
	ret0, _ := ret[0].(*entities.VolumeStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolumeStats indicates an expected call of GetVolumeStats.
func (mr *MockDashboardCacheServiceMockRecorder) GetVolumeStats(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolumeStats", reflect.TypeOf((*MockDashboardCacheService)(nil).GetVolumeStats), ctx, filter)
}

// InvalidateContext mocks base method.
func (m *MockDashboardCacheService) InvalidateContext(ctx context.Context, contextID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateContext", ctx, contextID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateContext indicates an expected call of InvalidateContext.
func (mr *MockDashboardCacheServiceMockRecorder) InvalidateContext(ctx, contextID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateContext", reflect.TypeOf((*MockDashboardCacheService)(nil).InvalidateContext), ctx, contextID)
}

// SetDashboardAggregates mocks base method.
func (m *MockDashboardCacheService) SetDashboardAggregates(ctx context.Context, filter entities.DashboardFilter, aggregates *entities.DashboardAggregates) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDashboardAggregates", ctx, filter, aggregates)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDashboardAggregates indicates an expected call of SetDashboardAggregates.
func (mr *MockDashboardCacheServiceMockRecorder) SetDashboardAggregates(ctx, filter, aggregates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDashboardAggregates", reflect.TypeOf((*MockDashboardCacheService)(nil).SetDashboardAggregates), ctx, filter, aggregates)
}

// SetMatchRateStats mocks base method.
func (m *MockDashboardCacheService) SetMatchRateStats(ctx context.Context, filter entities.DashboardFilter, stats *entities.MatchRateStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMatchRateStats", ctx, filter, stats)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMatchRateStats indicates an expected call of SetMatchRateStats.
func (mr *MockDashboardCacheServiceMockRecorder) SetMatchRateStats(ctx, filter, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMatchRateStats", reflect.TypeOf((*MockDashboardCacheService)(nil).SetMatchRateStats), ctx, filter, stats)
}

// SetMatcherDashboardMetrics mocks base method.
func (m *MockDashboardCacheService) SetMatcherDashboardMetrics(ctx context.Context, filter entities.DashboardFilter, metrics *entities.MatcherDashboardMetrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMatcherDashboardMetrics", ctx, filter, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMatcherDashboardMetrics indicates an expected call of SetMatcherDashboardMetrics.
func (mr *MockDashboardCacheServiceMockRecorder) SetMatcherDashboardMetrics(ctx, filter, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMatcherDashboardMetrics", reflect.TypeOf((*MockDashboardCacheService)(nil).SetMatcherDashboardMetrics), ctx, filter, metrics)
}

// SetSLAStats mocks base method.
func (m *MockDashboardCacheService) SetSLAStats(ctx context.Context, filter entities.DashboardFilter, stats *entities.SLAStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSLAStats", ctx, filter, stats)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSLAStats indicates an expected call of SetSLAStats.
func (mr *MockDashboardCacheServiceMockRecorder) SetSLAStats(ctx, filter, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSLAStats", reflect.TypeOf((*MockDashboardCacheService)(nil).SetSLAStats), ctx, filter, stats)
}

// SetVolumeStats mocks base method.
func (m *MockDashboardCacheService) SetVolumeStats(ctx context.Context, filter entities.DashboardFilter, stats *entities.VolumeStats) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVolumeStats", ctx, filter, stats)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetVolumeStats indicates an expected call of SetVolumeStats.
func (mr *MockDashboardCacheServiceMockRecorder) SetVolumeStats(ctx, filter, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVolumeStats", reflect.TypeOf((*MockDashboardCacheService)(nil).SetVolumeStats), ctx, filter, stats)
}
