// Code generated by MockGen. DO NOT EDIT.
// Source: object_storage.go
//
// Generated by this command:
//
//	mockgen -source=object_storage.go -destination=mocks/object_storage_client_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
