// Code generated by MockGen. DO NOT EDIT.
// Source: job_repository.go
//
// Generated by this command:
//
//	mockgen -source=job_repository.go -destination=mocks/job_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	http "github.com/LerianStudio/lib-commons/v4/commons/net/http"
	entities "github.com/LerianStudio/matcher/internal/ingestion/domain/entities"
	repositories "github.com/LerianStudio/matcher/internal/ingestion/domain/repositories"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockJobRepository is a mock of JobRepository interface.
type MockJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockJobRepositoryMockRecorder
	isgomock struct{}
}

// MockJobRepositoryMockRecorder is the mock recorder for MockJobRepository.
type MockJobRepositoryMockRecorder struct {
	mock *MockJobRepository
}

// NewMockJobRepository creates a new mock instance.
func NewMockJobRepository(ctrl *gomock.Controller) *MockJobRepository {
	mock := &MockJobRepository{ctrl: ctrl}
	mock.recorder = &MockJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRepository) EXPECT() *MockJobRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockJobRepository) Create(ctx context.Context, job *entities.IngestionJob) (*entities.IngestionJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, job)
	ret0, _ := ret[0].(*entities.IngestionJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockJobRepositoryMockRecorder) Create(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobRepository)(nil).Create), ctx, job)
}

// FindByContextID mocks base method.
func (m *MockJobRepository) FindByContextID(ctx context.Context, contextID uuid.UUID, filter repositories.CursorFilter) ([]*entities.IngestionJob, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByContextID", ctx, contextID, filter)
	ret0, _ := ret[0].([]*entities.IngestionJob)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByContextID indicates an expected call of FindByContextID.
func (mr *MockJobRepositoryMockRecorder) FindByContextID(ctx, contextID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByContextID", reflect.TypeOf((*MockJobRepository)(nil).FindByContextID), ctx, contextID, filter)
}

// FindByID mocks base method.
func (m *MockJobRepository) FindByID(ctx context.Context, id uuid.UUID) (*entities.IngestionJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entities.IngestionJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockJobRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockJobRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockJobRepository) Update(ctx context.Context, job *entities.IngestionJob) (*entities.IngestionJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, job)
	ret0, _ := ret[0].(*entities.IngestionJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockJobRepositoryMockRecorder) Update(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockJobRepository)(nil).Update), ctx, job)
}

// FindLatestByExtractionID mocks base method.
func (m *MockJobRepository) FindLatestByExtractionID(ctx context.Context, extractionID uuid.UUID) (*entities.IngestionJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestByExtractionID", ctx, extractionID)
	ret0, _ := ret[0].(*entities.IngestionJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestByExtractionID indicates an expected call of FindLatestByExtractionID.
func (mr *MockJobRepositoryMockRecorder) FindLatestByExtractionID(ctx, extractionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestByExtractionID", reflect.TypeOf((*MockJobRepository)(nil).FindLatestByExtractionID), ctx, extractionID)
}
