// Code generated by MockGen. DO NOT EDIT.
// Source: transaction_repository.go
//
// Generated by this command:
//
//	mockgen -source=transaction_repository.go -destination=mocks/transaction_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	http "github.com/LerianStudio/lib-commons/v5/commons/net/http"
	repositories "github.com/LerianStudio/matcher/internal/ingestion/domain/repositories"
	shared "github.com/LerianStudio/matcher/internal/shared/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTransactionRepository is a mock of TransactionRepository interface.
type MockTransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockTransactionRepositoryMockRecorder is the mock recorder for MockTransactionRepository.
type MockTransactionRepositoryMockRecorder struct {
	mock *MockTransactionRepository
}

// NewMockTransactionRepository creates a new mock instance.
func NewMockTransactionRepository(ctrl *gomock.Controller) *MockTransactionRepository {
	mock := &MockTransactionRepository{ctrl: ctrl}
	mock.recorder = &MockTransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionRepository) EXPECT() *MockTransactionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTransactionRepository) Create(ctx context.Context, tx *shared.Transaction) (*shared.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx)
	ret0, _ := ret[0].(*shared.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTransactionRepositoryMockRecorder) Create(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTransactionRepository)(nil).Create), ctx, tx)
}

// CreateBatch mocks base method.
func (m *MockTransactionRepository) CreateBatch(ctx context.Context, txs []*shared.Transaction) ([]*shared.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, txs)
	ret0, _ := ret[0].([]*shared.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockTransactionRepositoryMockRecorder) CreateBatch(ctx, txs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockTransactionRepository)(nil).CreateBatch), ctx, txs)
}

// ExistsBulkBySourceAndExternalID mocks base method.
func (m *MockTransactionRepository) ExistsBulkBySourceAndExternalID(ctx context.Context, keys []repositories.ExternalIDKey) (map[repositories.ExternalIDKey]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsBulkBySourceAndExternalID", ctx, keys)
	ret0, _ := ret[0].(map[repositories.ExternalIDKey]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsBulkBySourceAndExternalID indicates an expected call of ExistsBulkBySourceAndExternalID.
func (mr *MockTransactionRepositoryMockRecorder) ExistsBulkBySourceAndExternalID(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsBulkBySourceAndExternalID", reflect.TypeOf((*MockTransactionRepository)(nil).ExistsBulkBySourceAndExternalID), ctx, keys)
}

// ExistsBySourceAndExternalID mocks base method.
func (m *MockTransactionRepository) ExistsBySourceAndExternalID(ctx context.Context, sourceID uuid.UUID, externalID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsBySourceAndExternalID", ctx, sourceID, externalID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsBySourceAndExternalID indicates an expected call of ExistsBySourceAndExternalID.
func (mr *MockTransactionRepositoryMockRecorder) ExistsBySourceAndExternalID(ctx, sourceID, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsBySourceAndExternalID", reflect.TypeOf((*MockTransactionRepository)(nil).ExistsBySourceAndExternalID), ctx, sourceID, externalID)
}

// FindByID mocks base method.
func (m *MockTransactionRepository) FindByID(ctx context.Context, id uuid.UUID) (*shared.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*shared.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTransactionRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTransactionRepository)(nil).FindByID), ctx, id)
}

// FindByJobAndContextID mocks base method.
func (m *MockTransactionRepository) FindByJobAndContextID(ctx context.Context, jobID, contextID uuid.UUID, filter repositories.CursorFilter) ([]*shared.Transaction, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByJobAndContextID", ctx, jobID, contextID, filter)
	ret0, _ := ret[0].([]*shared.Transaction)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByJobAndContextID indicates an expected call of FindByJobAndContextID.
func (mr *MockTransactionRepositoryMockRecorder) FindByJobAndContextID(ctx, jobID, contextID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByJobAndContextID", reflect.TypeOf((*MockTransactionRepository)(nil).FindByJobAndContextID), ctx, jobID, contextID, filter)
}

// FindByJobID mocks base method.
func (m *MockTransactionRepository) FindByJobID(ctx context.Context, jobID uuid.UUID, filter repositories.CursorFilter) ([]*shared.Transaction, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByJobID", ctx, jobID, filter)
	ret0, _ := ret[0].([]*shared.Transaction)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindByJobID indicates an expected call of FindByJobID.
func (mr *MockTransactionRepositoryMockRecorder) FindByJobID(ctx, jobID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByJobID", reflect.TypeOf((*MockTransactionRepository)(nil).FindByJobID), ctx, jobID, filter)
}

// FindBySourceAndExternalID mocks base method.
func (m *MockTransactionRepository) FindBySourceAndExternalID(ctx context.Context, sourceID uuid.UUID, externalID string) (*shared.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySourceAndExternalID", ctx, sourceID, externalID)
	ret0, _ := ret[0].(*shared.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySourceAndExternalID indicates an expected call of FindBySourceAndExternalID.
func (mr *MockTransactionRepositoryMockRecorder) FindBySourceAndExternalID(ctx, sourceID, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySourceAndExternalID", reflect.TypeOf((*MockTransactionRepository)(nil).FindBySourceAndExternalID), ctx, sourceID, externalID)
}

// SearchTransactions mocks base method.
func (m *MockTransactionRepository) SearchTransactions(ctx context.Context, contextID uuid.UUID, params repositories.TransactionSearchParams) ([]*shared.Transaction, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTransactions", ctx, contextID, params)
	ret0, _ := ret[0].([]*shared.Transaction)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchTransactions indicates an expected call of SearchTransactions.
func (mr *MockTransactionRepositoryMockRecorder) SearchTransactions(ctx, contextID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTransactions", reflect.TypeOf((*MockTransactionRepository)(nil).SearchTransactions), ctx, contextID, params)
}

// UpdateStatus mocks base method.
func (m *MockTransactionRepository) UpdateStatus(ctx context.Context, id, contextID uuid.UUID, status shared.TransactionStatus) (*shared.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, contextID, status)
	ret0, _ := ret[0].(*shared.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockTransactionRepositoryMockRecorder) UpdateStatus(ctx, id, contextID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockTransactionRepository)(nil).UpdateStatus), ctx, id, contextID, status)
}
