// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/matching/domain/repositories (interfaces: AdjustmentRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/adjustment_repository_mock.go -package=mocks . AdjustmentRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	http "github.com/LerianStudio/lib-uncommons/v2/uncommons/net/http"
	entities "github.com/LerianStudio/matcher/internal/matching/domain/entities"
	repositories "github.com/LerianStudio/matcher/internal/matching/domain/repositories"
	shared "github.com/LerianStudio/matcher/internal/shared/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAdjustmentRepository is a mock of AdjustmentRepository interface.
type MockAdjustmentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdjustmentRepositoryMockRecorder
	isgomock struct{}
}

// MockAdjustmentRepositoryMockRecorder is the mock recorder for MockAdjustmentRepository.
type MockAdjustmentRepositoryMockRecorder struct {
	mock *MockAdjustmentRepository
}

// NewMockAdjustmentRepository creates a new mock instance.
func NewMockAdjustmentRepository(ctrl *gomock.Controller) *MockAdjustmentRepository {
	mock := &MockAdjustmentRepository{ctrl: ctrl}
	mock.recorder = &MockAdjustmentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdjustmentRepository) EXPECT() *MockAdjustmentRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdjustmentRepository) Create(ctx context.Context, adjustment *entities.Adjustment) (*entities.Adjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, adjustment)
	ret0, _ := ret[0].(*entities.Adjustment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAdjustmentRepositoryMockRecorder) Create(ctx, adjustment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdjustmentRepository)(nil).Create), ctx, adjustment)
}

// CreateWithAuditLog mocks base method.
func (m *MockAdjustmentRepository) CreateWithAuditLog(ctx context.Context, adjustment *entities.Adjustment, auditLog *shared.AuditLog) (*entities.Adjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithAuditLog", ctx, adjustment, auditLog)
	ret0, _ := ret[0].(*entities.Adjustment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithAuditLog indicates an expected call of CreateWithAuditLog.
func (mr *MockAdjustmentRepositoryMockRecorder) CreateWithAuditLog(ctx, adjustment, auditLog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithAuditLog", reflect.TypeOf((*MockAdjustmentRepository)(nil).CreateWithAuditLog), ctx, adjustment, auditLog)
}

// CreateWithAuditLogWithTx mocks base method.
func (m *MockAdjustmentRepository) CreateWithAuditLogWithTx(ctx context.Context, tx *sql.Tx, adjustment *entities.Adjustment, auditLog *shared.AuditLog) (*entities.Adjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithAuditLogWithTx", ctx, tx, adjustment, auditLog)
	ret0, _ := ret[0].(*entities.Adjustment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithAuditLogWithTx indicates an expected call of CreateWithAuditLogWithTx.
func (mr *MockAdjustmentRepositoryMockRecorder) CreateWithAuditLogWithTx(ctx, tx, adjustment, auditLog any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithAuditLogWithTx", reflect.TypeOf((*MockAdjustmentRepository)(nil).CreateWithAuditLogWithTx), ctx, tx, adjustment, auditLog)
}

// CreateWithTx mocks base method.
func (m *MockAdjustmentRepository) CreateWithTx(ctx context.Context, tx *sql.Tx, adjustment *entities.Adjustment) (*entities.Adjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, tx, adjustment)
	ret0, _ := ret[0].(*entities.Adjustment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockAdjustmentRepositoryMockRecorder) CreateWithTx(ctx, tx, adjustment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockAdjustmentRepository)(nil).CreateWithTx), ctx, tx, adjustment)
}

// FindByID mocks base method.
func (m *MockAdjustmentRepository) FindByID(ctx context.Context, contextID, id uuid.UUID) (*entities.Adjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, contextID, id)
	ret0, _ := ret[0].(*entities.Adjustment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAdjustmentRepositoryMockRecorder) FindByID(ctx, contextID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAdjustmentRepository)(nil).FindByID), ctx, contextID, id)
}

// ListByContextID mocks base method.
func (m *MockAdjustmentRepository) ListByContextID(ctx context.Context, contextID uuid.UUID, filter repositories.CursorFilter) ([]*entities.Adjustment, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByContextID", ctx, contextID, filter)
	ret0, _ := ret[0].([]*entities.Adjustment)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByContextID indicates an expected call of ListByContextID.
func (mr *MockAdjustmentRepositoryMockRecorder) ListByContextID(ctx, contextID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByContextID", reflect.TypeOf((*MockAdjustmentRepository)(nil).ListByContextID), ctx, contextID, filter)
}

// ListByMatchGroupID mocks base method.
func (m *MockAdjustmentRepository) ListByMatchGroupID(ctx context.Context, contextID, matchGroupID uuid.UUID) ([]*entities.Adjustment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMatchGroupID", ctx, contextID, matchGroupID)
	ret0, _ := ret[0].([]*entities.Adjustment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMatchGroupID indicates an expected call of ListByMatchGroupID.
func (mr *MockAdjustmentRepositoryMockRecorder) ListByMatchGroupID(ctx, contextID, matchGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMatchGroupID", reflect.TypeOf((*MockAdjustmentRepository)(nil).ListByMatchGroupID), ctx, contextID, matchGroupID)
}
