// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/matching/domain/repositories (interfaces: MatchItemRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/match_item_repository_mock.go -package=mocks . MatchItemRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/LerianStudio/matcher/internal/matching/domain/entities"
	repositories "github.com/LerianStudio/matcher/internal/matching/domain/repositories"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchItemRepository is a mock of MatchItemRepository interface.
type MockMatchItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMatchItemRepositoryMockRecorder
	isgomock struct{}
}

// MockMatchItemRepositoryMockRecorder is the mock recorder for MockMatchItemRepository.
type MockMatchItemRepositoryMockRecorder struct {
	mock *MockMatchItemRepository
}

// NewMockMatchItemRepository creates a new mock instance.
func NewMockMatchItemRepository(ctrl *gomock.Controller) *MockMatchItemRepository {
	mock := &MockMatchItemRepository{ctrl: ctrl}
	mock.recorder = &MockMatchItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchItemRepository) EXPECT() *MockMatchItemRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockMatchItemRepository) CreateBatch(ctx context.Context, items []*entities.MatchItem) ([]*entities.MatchItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, items)
	ret0, _ := ret[0].([]*entities.MatchItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockMatchItemRepositoryMockRecorder) CreateBatch(ctx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockMatchItemRepository)(nil).CreateBatch), ctx, items)
}

// CreateBatchWithTx mocks base method.
func (m *MockMatchItemRepository) CreateBatchWithTx(ctx context.Context, tx repositories.Tx, items []*entities.MatchItem) ([]*entities.MatchItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatchWithTx", ctx, tx, items)
	ret0, _ := ret[0].([]*entities.MatchItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatchWithTx indicates an expected call of CreateBatchWithTx.
func (mr *MockMatchItemRepositoryMockRecorder) CreateBatchWithTx(ctx, tx, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatchWithTx", reflect.TypeOf((*MockMatchItemRepository)(nil).CreateBatchWithTx), ctx, tx, items)
}

// ListByMatchGroupID mocks base method.
func (m *MockMatchItemRepository) ListByMatchGroupID(ctx context.Context, matchGroupID uuid.UUID) ([]*entities.MatchItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMatchGroupID", ctx, matchGroupID)
	ret0, _ := ret[0].([]*entities.MatchItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMatchGroupID indicates an expected call of ListByMatchGroupID.
func (mr *MockMatchItemRepositoryMockRecorder) ListByMatchGroupID(ctx, matchGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMatchGroupID", reflect.TypeOf((*MockMatchItemRepository)(nil).ListByMatchGroupID), ctx, matchGroupID)
}

// ListByMatchGroupIDs mocks base method.
func (m *MockMatchItemRepository) ListByMatchGroupIDs(ctx context.Context, matchGroupIDs []uuid.UUID) (map[uuid.UUID][]*entities.MatchItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByMatchGroupIDs", ctx, matchGroupIDs)
	ret0, _ := ret[0].(map[uuid.UUID][]*entities.MatchItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByMatchGroupIDs indicates an expected call of ListByMatchGroupIDs.
func (mr *MockMatchItemRepositoryMockRecorder) ListByMatchGroupIDs(ctx, matchGroupIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByMatchGroupIDs", reflect.TypeOf((*MockMatchItemRepository)(nil).ListByMatchGroupIDs), ctx, matchGroupIDs)
}
