// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/matching/domain/repositories (interfaces: MatchGroupRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/match_group_repository_mock.go -package=mocks . MatchGroupRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	http "github.com/LerianStudio/lib-commons/v4/commons/net/http"
	entities "github.com/LerianStudio/matcher/internal/matching/domain/entities"
	repositories "github.com/LerianStudio/matcher/internal/matching/domain/repositories"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchGroupRepository is a mock of MatchGroupRepository interface.
type MockMatchGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMatchGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockMatchGroupRepositoryMockRecorder is the mock recorder for MockMatchGroupRepository.
type MockMatchGroupRepositoryMockRecorder struct {
	mock *MockMatchGroupRepository
}

// NewMockMatchGroupRepository creates a new mock instance.
func NewMockMatchGroupRepository(ctrl *gomock.Controller) *MockMatchGroupRepository {
	mock := &MockMatchGroupRepository{ctrl: ctrl}
	mock.recorder = &MockMatchGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchGroupRepository) EXPECT() *MockMatchGroupRepositoryMockRecorder {
	return m.recorder
}

// CreateBatch mocks base method.
func (m *MockMatchGroupRepository) CreateBatch(ctx context.Context, groups []*entities.MatchGroup) ([]*entities.MatchGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, groups)
	ret0, _ := ret[0].([]*entities.MatchGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockMatchGroupRepositoryMockRecorder) CreateBatch(ctx, groups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockMatchGroupRepository)(nil).CreateBatch), ctx, groups)
}

// CreateBatchWithTx mocks base method.
func (m *MockMatchGroupRepository) CreateBatchWithTx(ctx context.Context, tx repositories.Tx, groups []*entities.MatchGroup) ([]*entities.MatchGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatchWithTx", ctx, tx, groups)
	ret0, _ := ret[0].([]*entities.MatchGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBatchWithTx indicates an expected call of CreateBatchWithTx.
func (mr *MockMatchGroupRepositoryMockRecorder) CreateBatchWithTx(ctx, tx, groups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatchWithTx", reflect.TypeOf((*MockMatchGroupRepository)(nil).CreateBatchWithTx), ctx, tx, groups)
}

// FindByID mocks base method.
func (m *MockMatchGroupRepository) FindByID(ctx context.Context, contextID, id uuid.UUID) (*entities.MatchGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, contextID, id)
	ret0, _ := ret[0].(*entities.MatchGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMatchGroupRepositoryMockRecorder) FindByID(ctx, contextID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMatchGroupRepository)(nil).FindByID), ctx, contextID, id)
}

// ListByRunID mocks base method.
func (m *MockMatchGroupRepository) ListByRunID(ctx context.Context, contextID, runID uuid.UUID, filter repositories.CursorFilter) ([]*entities.MatchGroup, http.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRunID", ctx, contextID, runID, filter)
	ret0, _ := ret[0].([]*entities.MatchGroup)
	ret1, _ := ret[1].(http.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByRunID indicates an expected call of ListByRunID.
func (mr *MockMatchGroupRepositoryMockRecorder) ListByRunID(ctx, contextID, runID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRunID", reflect.TypeOf((*MockMatchGroupRepository)(nil).ListByRunID), ctx, contextID, runID, filter)
}

// Update mocks base method.
func (m *MockMatchGroupRepository) Update(ctx context.Context, group *entities.MatchGroup) (*entities.MatchGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, group)
	ret0, _ := ret[0].(*entities.MatchGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMatchGroupRepositoryMockRecorder) Update(ctx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMatchGroupRepository)(nil).Update), ctx, group)
}

// UpdateWithTx mocks base method.
func (m *MockMatchGroupRepository) UpdateWithTx(ctx context.Context, tx repositories.Tx, group *entities.MatchGroup) (*entities.MatchGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithTx", ctx, tx, group)
	ret0, _ := ret[0].(*entities.MatchGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWithTx indicates an expected call of UpdateWithTx.
func (mr *MockMatchGroupRepositoryMockRecorder) UpdateWithTx(ctx, tx, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithTx", reflect.TypeOf((*MockMatchGroupRepository)(nil).UpdateWithTx), ctx, tx, group)
}
