// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/LerianStudio/matcher/internal/matching/domain/repositories (interfaces: MatchRunRepository)
//
// Generated by this command:
//
//	mockgen -imports=libHTTP=github.com/LerianStudio/lib-uncommons/v2/uncommons/net/http -destination=mocks/match_run_repository_mock.go -package=mocks . MatchRunRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	libHTTP "github.com/LerianStudio/lib-uncommons/v2/uncommons/net/http"
	entities "github.com/LerianStudio/matcher/internal/matching/domain/entities"
	repositories "github.com/LerianStudio/matcher/internal/matching/domain/repositories"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMatchRunRepository is a mock of MatchRunRepository interface.
type MockMatchRunRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMatchRunRepositoryMockRecorder
	isgomock struct{}
}

// MockMatchRunRepositoryMockRecorder is the mock recorder for MockMatchRunRepository.
type MockMatchRunRepositoryMockRecorder struct {
	mock *MockMatchRunRepository
}

// NewMockMatchRunRepository creates a new mock instance.
func NewMockMatchRunRepository(ctrl *gomock.Controller) *MockMatchRunRepository {
	mock := &MockMatchRunRepository{ctrl: ctrl}
	mock.recorder = &MockMatchRunRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchRunRepository) EXPECT() *MockMatchRunRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMatchRunRepository) Create(ctx context.Context, entity *entities.MatchRun) (*entities.MatchRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(*entities.MatchRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMatchRunRepositoryMockRecorder) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMatchRunRepository)(nil).Create), ctx, entity)
}

// CreateWithTx mocks base method.
func (m *MockMatchRunRepository) CreateWithTx(ctx context.Context, tx repositories.Tx, entity *entities.MatchRun) (*entities.MatchRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", ctx, tx, entity)
	ret0, _ := ret[0].(*entities.MatchRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockMatchRunRepositoryMockRecorder) CreateWithTx(ctx, tx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockMatchRunRepository)(nil).CreateWithTx), ctx, tx, entity)
}

// FindByID mocks base method.
func (m *MockMatchRunRepository) FindByID(ctx context.Context, contextID, runID uuid.UUID) (*entities.MatchRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, contextID, runID)
	ret0, _ := ret[0].(*entities.MatchRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockMatchRunRepositoryMockRecorder) FindByID(ctx, contextID, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockMatchRunRepository)(nil).FindByID), ctx, contextID, runID)
}

// ListByContextID mocks base method.
func (m *MockMatchRunRepository) ListByContextID(ctx context.Context, contextID uuid.UUID, filter repositories.CursorFilter) ([]*entities.MatchRun, libHTTP.CursorPagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByContextID", ctx, contextID, filter)
	ret0, _ := ret[0].([]*entities.MatchRun)
	ret1, _ := ret[1].(libHTTP.CursorPagination)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByContextID indicates an expected call of ListByContextID.
func (mr *MockMatchRunRepositoryMockRecorder) ListByContextID(ctx, contextID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByContextID", reflect.TypeOf((*MockMatchRunRepository)(nil).ListByContextID), ctx, contextID, filter)
}

// Update mocks base method.
func (m *MockMatchRunRepository) Update(ctx context.Context, entity *entities.MatchRun) (*entities.MatchRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(*entities.MatchRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMatchRunRepositoryMockRecorder) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMatchRunRepository)(nil).Update), ctx, entity)
}

// UpdateWithTx mocks base method.
func (m *MockMatchRunRepository) UpdateWithTx(ctx context.Context, tx repositories.Tx, entity *entities.MatchRun) (*entities.MatchRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithTx", ctx, tx, entity)
	ret0, _ := ret[0].(*entities.MatchRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWithTx indicates an expected call of UpdateWithTx.
func (mr *MockMatchRunRepositoryMockRecorder) UpdateWithTx(ctx, tx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithTx", reflect.TypeOf((*MockMatchRunRepository)(nil).UpdateWithTx), ctx, tx, entity)
}

// WithTx mocks base method.
func (m *MockMatchRunRepository) WithTx(ctx context.Context, fn func(repositories.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockMatchRunRepositoryMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockMatchRunRepository)(nil).WithTx), ctx, fn)
}
