name: "Build"

on:
  push:
    tags:
      - '**'

jobs:
  build:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/build.yml@v1.15.0
    with:
      runner_type: "blacksmith-4vcpu-ubuntu-2404"
      enable_dockerhub: true
      enable_ghcr: true
      dockerhub_org: lerianstudio
      enable_gitops_artifacts: true
    secrets: inherit

  update_gitops:
    needs: [build]
    if: needs.build.result == 'success'
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/gitops-update.yml@v1.17.0
    with:
      runner_type: "firmino-lxc-runners"
      artifact_pattern: "gitops-tags-matcher"
      deploy_in_firmino: true
      deploy_in_clotilde: true
      yaml_key_mappings: '{"matcher.tag": ".matcher.image.tag"}'
    secrets: inherit
