name: "PR Security Scan"

on:
  pull_request:
    branches:
      - develop
      - release-candidate
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'
      - 'LICENSE'
      - 'CODEOWNERS'
      - '.gitignore'
      - 'images/**'
      - '*.txt'

jobs:
  security-scan:
    uses: LerianStudio/github-actions-shared-workflows/.github/workflows/pr-security-scan.yml@3197048995e33cfe9880a4c2c76c20f4cf9bd3ef # v1.26.3
    with:
      runner_type: "blacksmith-4vcpu-ubuntu-2404"
      dockerhub_org: "lerianstudio"
    secrets: inherit
